### ISSUE TITLE
function redefined even if 0:

### ISSUE THREAD

**Issue by JohnDenker** [atsepkov/RapydScript#101]
#### Context
```
def bartrue(): print("bar OK")
def barfalse(): print("bar not OK")

if 1:
  def foo():  print("foo OK")
  bar = bartrue
else:
  def foo():  print("foo not OK")
  bar = barfalse
bar()
foo()
```
#### Expected and Desired Behavior (ordinary python)
```
bar OK
foo OK
```
#### Observed Behavior (RS)
```
bar OK
foo not OK
```
#### Possible workaround
See bar() above.  Define differently-named functions, and then do a simple assign.

#### Discussion
It is not necessary to tell me that this is a reflection of the creepy underlying js behavior.  The point is, it would be nice if  RS could protect users from the creepy underlying js behavior.

Constructive suggestion:  if RS generated ``foo = function(){}`` rather than ``function foo(){}`` the resulting behavior would be a lot more pythonic.

**Comment by kovidgoyal** [comment]
Using foo = function would mean that you would not get function names in tracebacks, a cost far higher than this creepy behavior. And note that the linter will warn you about this construct (defining functions in conditional branches.

**Comment by JohnDenker** [comment]
OK, that's an interesting point.

Taking the next step down that road ... can we not have our cake and eat it too?  Has anybody considered munging the function names, perhaps along the following lines?
```
if (1) {
    function foo() {                             # bad: not munged
        console.log("foo OK");
    }
    bar = function bar__$00001(){    # good: munged
        console.log("bar OK");
    }
    gripe = function gripe__$00002(){
        console.log("gripe OK");
        throw new Error("as requested")
    }

} else {
    function foo() {
        console.log("foo not OK");
    }
    bar = function bar__$00003(){
        console.log("bar not OK");
    }
    gripe = function gripe__$00004(){
        console.log("gripe not OK");
        throw new Error("bad bad bad")
    }
}
bar()
foo()
gripe()
```
#### Observed Behavior:
```
bar OK
foo not OK
gripe OK
/mnt/more/jsd/physics/play-if-def.js:10
        throw new Error("as requested")
              ^
Error: as requested
    at gripe__$00001 (/mnt/more/jsd/physics/play-if-def.js:10:15)
    at Object.<anonymous> (/mnt/more/jsd/physics/play-if-def.js:27:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
#### Discussion

It seems this allows pythonic semantics ***and*** decent tracebacks.  As long as the js exception is traceable back to the relevant python source line, I don't mind that the js function name has been munged.

**Comment by kovidgoyal** [comment]
You'll have to convince @atsepkov last time I had this discussion with him, he was adamant that defining functions in conditional blocks is an anti-pattern. I did not care enough to argue the point, since I wrote a check into the linter that makes it easy to find and fix these occurrences by hand. 

The compiler could probably be modified to use function expressions if inside a conditional and not in an assignment rhs, but, whether that is a something to be desired or not, is another question.

**Comment by atsepkov** [comment]
The original discussion can be found in #69. Calling that response adamant is a stretch at best. I still believe that conditional definitions are an anti-pattern and linter does throw an warning about that (in addition to the error thrown by strict mode, which RS defaults to). Perhaps, as Kovid mentioned in the other thread, compiler should too. I would actually like to modify the linter to have the concept of "severe" and "minor" errors, where severe are thrown at compile time by default.
