### ISSUE TITLE
Cannot declare an external class in version 0.3.9  

### ISSUE THREAD

**Issue by jpcharlesworth** [atsepkov/RapydScript#105]
I have just upgraded my Rapydscript installation via npm upgrade and I can no longer compile my applications because the first line, which is

    @external

produces the error Unexpected token: name external.

I am using compile options -b -p -m

I also note that Rapydscript is now wanting node version 0.12.0 and wondering whether it will still run on 0.10.26.

This also raises the question of whether it is possible to downgrade to earlier versions in cases like this.

**Comment by kovidgoyal** [comment]
@atsepkov should fix this fork soon enough (he usually only works on RS on weekends). In the meantime you can always checkout a previous version from git and use that. Instructions for installing from git are in the readme of my fork, I dont know whether @atsepkov has added them to the readme of this fork, as yet.

**Comment by jpcharlesworth** [comment]
Thanks Kovid, I have checked the latest repo from git and installed it according to the instructions on rapydscript-ng. I have found a version that works at commit d30a2733 and one that doesn't at commit 10860f34. All the commits between those two are taken from your version, Kovid, dated between June 22 and July 3.

**Comment by kovidgoyal** [comment]
Af ras as I know, this bug does not exist in my fork. Since @atsepkov has been doing partial merges (not his fault, just a result of the forks having diverged a lot), it's not surprising some things break, you will have to wait till he has time to fix this fork.

**Comment by atsepkov** [comment]
Looking at this right now. `@external` still compiles and works for me, but I did notice that I'm only handling the decorator on classes, not functions. Can you provide more context?

One other possibility I'm thinking of is if you're using external modules, which I supported at one point but have been removed by the new import system introduced right around the time of the commits you mentioned, but there should be a lot more in those commits.

**Comment by jpcharlesworth** [comment]
Sorry, I should have given you more context in the first place but it looked as if @export had just gone missing.
Here is an extract from the code which should explain what I'm doing. 

   @external
   module JSONRPC:
       class JSONProxy:
           pass

    class LocalPHPService(JSONRPC.JSONProxy):
        def __init__(self, controller, methodList):
            url = "../php_services/" + controller + ".php"
            JSONRPC.JSONProxy.__init__(self, url, methodList)

    class MyApp(Object):
        def __init__(self, dbName = None):
            rt_methods = ["echo","rorcCheck","updateRatingDb"]
            local_rtservice = LocalPHPService("RatingService", rt_methods)
            ......
            .......
           local_rtservice.echo('This is a test',self)

JSONRPC is a javascript module that implements the JSONRPC protocol for calling procedures on the server. It defines a class JSONProxy. To use a JSONRPC service, you create an instance of JSONProxy, giving it the url of the service and a list of methods that the service exposes. My class LocalPHPService is inheriting from JSONRPC.JSONProxy so that I can conveniently create proxies to several services running at different urls and with different method lists. All of it is a straight lift from pyjamas code that was essentially identical apart from the import mechanism. The JSONRPC module is pulled in by a script tag in the HTML file. 

This did not work in very early versions of RapydScript and there was detailed discussion of of the problem on several occasions,  but it was eventually resolved by 
https://groups.google.com/forum/#!topic/rapydscript/N_fFfUjxTcY

Reading the current README.md suggests that, while one can still declare classes external, the ability to do so with modules (i.e. functions) has disappeared, as you seem to be saying in your post of yesterday. Is it possible to restore that?

**Comment by kovidgoyal** [comment]
The import system has changed completely, and module is no longer a keyword (at least in my fork -- most of the import system changes have been imported into this fork as well, AFAIK). importing in rapydscript works just like in python now. 

If you want to mark a name as a class that is defined in some non-rapydscript code, you just do

```py
@external
class XYZ:
  pass
```

**Comment by jpcharlesworth** [comment]
I have tried what you suggest and that certainly allows it to compile. However, The code will not run at all in node-webkit. It runs only 12 lines in Chrome on localhost because it regards the characters which are the prefix to certain baselib functions, notably the print function, as illegal tokens.

**Comment by kovidgoyal** [comment]
That is again something specific to this fork. I'm guessing it is because of this commit:
https://github.com/atsepkov/RapydScript/commit/61a1d680c0d5c9325db7ce42acda0a6d2e83640e

As I commented on that commit, (see third comment) doing this is not safe on older JS runtimes.

**Comment by jpcharlesworth** [comment]
Even if I can get round the problem of the renaming of baselib functions (how?), the latest master is not compiling my LocalPHPService class correctly.

    class LocalPHPService(JSONRPC.JSONProxy):
        def __init__(self, controller, methodList):
            url = "../php_services/" + controller + ".php"
            JSONRPC.JSONProxy.__init__(self, url, methodList)

is compiling to 

    function LocalPHPService() {
        LocalPHPService.prototype.__init__.apply(this, arguments);
    }
    ՐՏ_extends(LocalPHPService, JSONRPC.JSONProxy);
    LocalPHPService.prototype.__init__ = function __init__(controller, methodList){
        var self = this;
        var url;
        url = "../php_services/" + controller + ".php";
        JSONRPC.JSONProxy.__init__(self, url, methodList);
    };

whereas it used to compile to 

    function LocalPHPService() {
        LocalPHPService.prototype.__init__.apply(this, arguments);
    }
    _$rapyd$_extends(LocalPHPService, JSONRPC.JSONProxy);
    LocalPHPService.prototype.__init__ = function __init__(controller, methodList){
        var self = this;
        var url;
        url = "../php_services/" + controller + ".php";
        JSONRPC.JSONProxy.prototype.constructor.call(self, url, methodList);
    };

JSONRPC.JSONProxy has no __init__ method.

**Comment by atsepkov** [comment]
So as suspected external modules were the culprit of original problem. As Kovid mentioned, I've removed them from the language because with Pythonic import it didn't seem like it was needed anymore - same reason that Kovid removed them from his fork. I did not think of your use case, however. If there is no cleaner way to handle this use-case, we can talk about adding it back in. All a module is is a function with all its variables exposed at the end.

As far as illegal characters, can you do a mass-replace of "ՐՏ_" in your code with "_$rapyd$_" and see if that fixes the issue. I'm that node-webkit complains about them since they're legal according to ES5 standard (the again, this wouldn't be the first time the standard is ignored).

As for your example, are you referring to `contstructor` being replaced with `__init__`? That was changed to support args/kwargs on constructors (a different bug). Perhaps we should still compile to `constructor` for `external` classes.

**Comment by atsepkov** [comment]
Also, as far as node 0.10, I've updated to 0.12 because I didn't want to support older version, but as far as I'm aware there is nothing in the codebase that's not supported by 0.10, yet. The 0.10 version does fail a unit test last time I checked (for repl, I believe). And as I start adding ES6 features (generators, etc.), 0.10 will not support them. If it works for you, feel free to continue using it, but I don't want the project to be held back by it (for similar reasons as not wanting IE6 to dictate what methods the browser has available to it).

**Comment by jpcharlesworth** [comment]
Thanks for your response - it's beginning to sound like it can be sorted out. I would certainly be grateful if the module declaration, or something with the same effect, could be restored and would result in a proper constructor call.

I will try doing a global replace of the offending characters in the baselib names but it may be a day or two before I get to it

It may be that the latest version of node-webkit will handle those characters but I am temporarily stuck with 0.8.6, which is quite old, because I would have to upgrade node and also do a new build of node_sqlite3, which is a bit hairy, in order to use the recent versions of node-webkit. Also my stuff runs on a normal server and I have the latest version of Chrome and that didn't like the characters, so I wouldn't place any bets on node-webkit working.

One good thing is that I've been forced to work from a Git clone, instead of upgrading from npm, so that now I can easily backtrack if an upgrade causes problems. Hence I am still in production,m although with a version several months old.

**Comment by atsepkov** [comment]
I can also abstract that away easily so user can overwrite the prefix character (or allow a flag to modify it, or .rsconfig file - which actually may be useful for defining linter rules as well). My Chrome version (Version 45.0.2454.85 Built on Ubuntu 14.04, running on LinuxMint 17.2 (64-bit)) handles the prefix without problems.

**Comment by kovidgoyal** [comment]
The linter already reads setup.cfg (similar to pyflakes).

**Comment by kovidgoyal** [comment]
As for __init__ vs constructor, IMO compiling XYZ.__init__(whatever) to XYZ.prototype.constructor.call(self, whatever) is XYZ is external, is too much magic. Imagine if XYZ actually has an __init__ method you wish to call, then the only way to do it would be to include literal javascript.

**Comment by atsepkov** [comment]
Not the main-branch linter. I didn't copy that logic in yet. I do agree with you on the magic, since external could be another RS library, so this isn't necessarily what the user wants. The verbatim `JS()` approach you mention is a good alternative.

**Comment by jpcharlesworth** [comment]
I'm please to be able to report some encouraging progress.
I have used a JS() call to force the production of JSONRPC.JSONProxy.prototype.constructor.call(args); so the removal of module is no longer an issue for me. 
I have included charset='UTF-8' in the relevant script tags and Chrome now correctly recognises the new prefix. 
As a result, after rebuilding all relevant modules with the master branch, I can now run one of my applications in both Chrome and Firefox (latest versions on Windows 7). I have not exhaustively tested it but I'm fairly confident it's OK .

I have not got very far yet with node_webkit but it now runs far enough for me to use the developer tools and I think it is recognising the prefix OK, so I am hopeful that it will work when I have rebuilt some further modules which the node-webkit version needs in addition to the ones for the browser.

It seems therefore that the new prefix is not going to be a problem, at least in a controlled running environment. However, a couple of my applications run on a website and are frequently accessed via tablets and mobile phones, as well as by people who may not have updated their browsers. When I have got to the stage where I can run everything with the new version I will try to test that and will report any problems.

**Comment by atsepkov** [comment]
Glad to hear that, keep me updated and if the new prefix does turn out to be a problem, we can fix that as well.

**Comment by jpcharlesworth** [comment]
I also have Node-Webkit 0.8.6 working as well now. The issues were exactly the same as with the browser.

Over the next few days I hope to update my whole body of applications and I shall be surprised if I come across any different issues; if I do, I will report them and If not, I will report successful completion.

**Comment by jpcharlesworth** [comment]
I have now update all my applications without finding any other issues during testing on Chrome, Firefox and Node-Webkit 0.8.6. I would be happy for this issue to be closed now. If I find any new problems when I get around to posting the new versions on the web and testing on mobile devices, I will open a new issue, if necessary.

**Comment by atsepkov** [comment]
Glad to hear that, thanks for your patience and putting up with growing pains of the language.
