### ISSUE TITLE
An external class does not seem to work in an imported module.

### ISSUE THREAD

**Issue by jpcharlesworth** [atsepkov/RapydScript#106]
In the main file of a working application I have this code

    @external
    class JSONProxy
        pass

    class LocalPHPService(JSONRPC.JSONProxy):
        def __init__(self, controller, methodList):
            url = "../php_services/" + controller + ".php"
            JS('JSONRPC.JSONProxy.prototype.constructor.call(self, url, methodList)')

    class MyApp(Object):
        def __init__(self):
            self.local_rmservice = LocalPHPService("RMService", ["echo", "getDbPath"])

This also works without the @external declaration provided new is inserted before the call to LocalPHPService.

If I move the code preceding class MyApp into a file JSONRPCServices.pyj and then at the beginning of the main application insert

     from JSONRPCServices import LocalPHPService

the code compiles OK but, when run, fails with the error message 

    Uncaught ReferenceError: JSONProxy is not defined 

It still fails this way if the @external declaration is retained in the main file.
Inserting new in front of the call to instantiate LocalPHPService does not cure the problem

This is not an urgent problem, just reporting what seems to be an anomaly.

**Comment by kovidgoyal** [comment]
I'm somewhat confused. As far as I can tell you are using JSONRPC is defined in an external library and added to the global object. And JSONProxy is a property on JSONRPC. From the error you posted it seems like JSONProxy is not defined at the time the imported code is run, are you using async scripts? Because that's the only way I can think of for that to happen.

**Comment by kovidgoyal** [comment]
Note that @external does not affect attribute access at all. It is only used to avoid having to write the new operator in RapydScript. As far as I can see there is no new operator in any of the code you posted, so $external is not needed at all.

**Comment by jpcharlesworth** [comment]
@kovidgoyal 

In your first comment, the first two sentences are correct. However, JSONRPC is pulled in by a script tag in the HTML and is definitely defined when the imported code is run.

As regards your second comment, I understand the purpose of @external. In the code I posted at the top of my description of the issue, there is no *new* operator precisely because JSON proxy is declared to be an external class. If I remove the @external declaration then I __do__ have to use new and  write 

        self.local_rmservice =  new LocalPHPService("RMService", ["echo", "getDbPath"])

However, I have managed to pin down the problem to a specific construct in the javascript code.
As you will be aware, importing an RS module produces a self executing wrapping function which encloses the compiled version of the imported code. At the end of the function, appropriate properties of the ՐՏ_modules object are defined which, in effect, export to the importing code the functions and objects defined in the imported code.
So, with the code in my original post, the line

     from JSONRPCServices import LocalPHPService

produces code in the wrapping function which finishes with

    ՐՏ_modules["JSONRPCServices"]["JSONProxy"] = JSONProxy;

    ՐՏ_modules["JSONRPCServices"]["LocalPHPService"] = LocalPHPService;

But JSONProxy is not defined in the wrapped code or in the global context. It is a property of the JSONRPC object which __is__ defined in the global context. So changing the first of the two code lines above to 

    ՐՏ_modules["JSONRPCServices"]["JSONProxy"] = JSONRPC.JSONProxy;

makes it work.

However, it turns out that there is a better solution.

After the import wrapping functions, there is a section where the imported objects are redeclared.
So we find, for that
 
     from JSONRPCServices import LocalPHPService

produces

    var RemotePHPService = ՐՏ_modules["JSONRPCServices"].RemotePHPService;

If I change the import line to

     from JSONRPCServices import JSONProxy, LocalPHPService

then I get, instead

    var JSONProxy = ՐՏ_modules["JSONRPCServices"].JSONProxy;
    var RemotePHPService = ՐՏ_modules["JSONRPCServices"].RemotePHPService;

And that makes the application work.

Maybe it should have been obvious to me that I needed to do that but it was only as I was writing this post that the idea occurred to me.

So there is nothing wrong with importing code that refers to external modules, as long as you understand what you have to do. I would close the issue but you may wish to make a further comment, so I will not close it immediately.

**Comment by kovidgoyal** [comment]
The bit that is confusing me, is why you need an @external declaration at all. For instance, the following code:

```py
class LocalPHPService(JSONRPC.JSONProxy):
    def __init__(self, controller, methodList):
        url = "../php_services/" + controller + ".php"
        JSONRPC.JSONProxy.prototype.constructor.call(self, url, methodList)

class MyApp(Object):
    def __init__(self):
        self.local_rmservice = LocalPHPService("RMService", ["echo", "getDbPath"])
```

generates (using my fork)

```js
(function(){
    "use strict;";

    (function(){

        var __name__ = "__main__";


        var MyApp;
        function LocalPHPService() {
            LocalPHPService.prototype.__init__.apply(this, arguments);
        }
        _$rapyd$_extends(LocalPHPService, JSONRPC.JSONProxy);
        LocalPHPService.prototype.__init__ = function __init__(controller, methodList) {
            var self = this;
            var url;
            url = "../php_services/" + controller + ".php";
            JSONRPC.JSONProxy.prototype.constructor.call(self, url, methodList);
        };

        function MyApp() {
            MyApp.prototype.__init__.apply(this, arguments);
        }
        _$rapyd$_extends(MyApp, Object);
        MyApp.prototype.__init__ = function __init__() {
            var self = this;
            self.local_rmservice = new LocalPHPService("RMService", _$rapyd$_list_decorate([ "echo", "getDbPath" ]));
        };

    })();
})();
```

As you can see there is no @external anywhere in the picture and the new operator is correctly output regardless when creating `self.local_rmservice`. 

So in other words, you dont need @external for your use case, as far as I can tell.

**Comment by jpcharlesworth** [comment]
Now I'm confused because I was sure I had demonstrated to myself that, in the original non-import code, you either had to have the @external declaration or you had to use new when creating an instance of LocalPHPService. However, I can't demonstrate that now, because, as you say , the __new__ is getting inserted automatically even without the @external.

More interesting is the fact that if you remove the @external declaration of JSONProxy from the JSONRPCServices module then you no longer have to import JSONProxy to make the application work. So as you say, you don't need @external anywhere and, furthermore, putting it in actually causes trouble because it forces you to pointlessly import the class you've declared to be external.

So when would you want to use @external and why is it not needed here? Well I suppose if you were going to create instances of the actual external class itself, you might use it to save having in insert __new__ every time you did that. In the present case we are only creating an instance of a derived class and, for that case, RS can figure out for itself that it needs to insert __new__ and that's not affected by whether it knows anything about the base class.

Thanks for your help. Is there anything more to say about this issue?

**Comment by kovidgoyal** [comment]
Dunno, if this helps, but in the original code you posted, you are missing a semi-colon after 

`class JSONProxy`

But, yes, this bug report can be closed now, as far as I am concerned.

**Comment by atsepkov** [comment]
@jpcharlesworth sorry I'm late to the conversation, but to answer your question:

`@external` keyword marks the object (previously module or class, currently only class, although for linter's sake we should probably do the same with functions) as declared elsewhere, so that the compiler is aware of it.

At its core, all this decorator does is prevent the object it's used on from being printed to the output, while still setting all the flags that this declaration would typically trigger. As a result (mainly because of RapydScript's flags) it has a number of use cases:

- mark an external object (i.e. CasperJS/PhantomJS) as a class, allowing automatic insertion of `new` keyword
- trigger addition of certain baselib library that you need either in this module or another module you're stitching together (typically also requires `--bare` flag to avoid scope-guard)
- handle non-traditional importing (i.e. including multiple js files in a single page)
- avoid "undeclared variable" errors from linter
