### ISSUE TITLE
Embedding rapydscript to the webpage

### ISSUE THREAD

**Issue by mardon86** [atsepkov/RapydScript#108]
Hi, @atsepkov  i have an idea to embed rapydscript to the webpage. So that we could program and write JS in RapydScript code on the fly like Brython does. What do you think ?

Check this out ! https://github.com/mardon86/RapydScript_onwebpage

So far,,
- i'm loading rapydscript code as string via "xxxx" variable in file mycode.pyj
- I dont know how to load Rapydscript file automatically via `<script type="text/rapydscript" src="mycode.pyj"></script>` and treat the code inside as rapydscript code
- it returns into error when i'm using option "omit_baselib": false

I'm sure you can do better and i hope you could post official guide to embed rapydscript to the webpage

**Comment by atsepkov** [comment]
It already runs in the browser: http://www.rapydscript.com/try-it/

Although that's admittedly a dated version that I need to update (and instructions have changed a bit since then). If you want a similar compiler with latest build, here are two alternatives that should work (not tested, so instructions may differ slightly):

# Method 1
When you compile rapydscript, it generates 5 files in `lib`: output.js, parse.js, ast.js, utils.js, and baselib.js. Include each one on the page via `src` tag (or concatenate them into a single file). You then want to run a similar "eval" loop as repl.js does in the browser, mainly:

    # generate a tree of logic
    astTree = RapydScript.parse(source, input_options) # this functionality is from parse.js (also relies on ast.js)
    # output to JS
    outputGenerator = RapydScript.OutputStream(output_options) # this functionality is from output.js (also relies on ast.js)
    astTree.print(outputGenerator)
    js = outputGenerator.toString()
    # execute
    eval(js)

# Method 2 (cleaner, but longer)
At the top of parse.pyj and output.pyj, import everything from utils and ast (note that * imports are not supported):

    from ast import AST_Scope, ...

Create a new file that imports from parse and output and performs the same logic as method 1 in RapydScript. Compile that file via RapydScript. Now you have a single file you can embed in a webpage that will compile anything for you.

**Comment by mardon86** [comment]
code:
`for i in range(10):
    print(i)
`
using the first mode with default option "omit_baselib": false, resulting this error : TypeError: options.baselib is null

what the value of options.baselib supposed to ?

**Comment by charleslaw** [comment]
I hesitate a little to post this but I believe I have this working in this repo & branch: https://github.com/charleslaw/RapydScript_web/tree/feature/latest_rapyd

The reason I hesitate is that it's not fully tested, and not everything is updated (README, other html files, pathc files, etc), but index.html should work.  If you do use this, please let me know if you find any bugs.

**Comment by mardon86** [comment]
@charleslaw Yup its working, thx,, i didn't know that somebody has the idea of using rapydscript on the web too,, and that's far before me :D

After looking into your index.html code, i found that i'm missing option {"baselib": "."} in the OutputStream()
Now, my code (using @atsepkov 's first method) also works,,

Thx..

**Comment by mardon86** [comment]
Now, is there a way to load rapydscript file via `<script type="text/rapydscript" src="mycode.pyj"></script>` and treat the code inside of it as rapydscript code (not javascript) ?

**Comment by hartsantler** [comment]
@mardon86, now that you have rapydscript running in the browser, you should be able to easily translate rs code client side with something like this:
```html
<head>
<script type="text/rapydscript" id="MYSCRIPT">
def foobar(): print 'hello world'
</script>

<script>
function translate_rs() {
  var code = document.getElementById('MYSCRIPT');
  ... translate code here into js and eval it ...
}
</script>
</head>
<body onload="translate_rs()">
...
```

**Comment by mardon86** [comment]
@hartsantler thx,, i found that i must do XMLHTTPRequest to get the content of the .pyj file via src script tag. And that definitly wont work if i run the webpage locally without running HTTP Server.
I think i'll stick with treating rapydscript code as javascript string. And put the code with some extra boilerplate like this:
```
<script id="hello">rs_eval(`

        def():
          def do_this():
            document.getElementById("output").inlineHTML = "Hello, from RapydScript"

          document.addEventListener("DOMContentLoaded", do_this);
        .call()

`);</script>
```

**Comment by adousen** [comment]
@mardon86 
You can take a look at my solution pyjTransformer,  compiles .pyj files or rapydscript code  to javascript:
https://github.com/adousen/RapydScript-pyjTransformer

**Comment by atsepkov** [comment]
Just an FYI, I will do some refactoring in the next few weeks to get the same codebase working in web without patches. At this point in time, there is no reason why the logic should be different.

**Comment by atsepkov** [comment]
**Update**:, with new compilation method, this should now (in theory) work out of the box. include the generated lib/rapydscript.js on your page, require it using something like browserify and call `rapydscript.compile(code, options)` to get a string of compiled javascript. The only remaining gotcha is import of baselib, which I should modify to be compatible with the web as well before closing this task.

**Comment by atsepkov** [comment]
As of commit 0d393d88b84e34efa0a52bcff97f714f573ad517 this now works with the exact same module. `lib/rapydscript.js` is what node uses to do its compilation, same exact file can now be included in a web page and invoked as follows:

```
rapydscript.compile(stringOfCode, options)
```

**Comment by mardon86** [comment]
Thx @atsepkov, how to get the minified version of the rapydscript.js ? I tried to compress it on jscompress.com but the minified version resulting a punctuation error. I also tried to compress the 0.4.4 version. All files (baselib, utils, ast, output, tokenizer) seem to work well except parser.js. Resulting the same error if i use the minified version of parser.js thx

**Comment by atsepkov** [comment]
If you're compressing the files individually, you're either using an outdated version or not doing something right, https://github.com/atsepkov/RapydScript/blob/master/lib/rapydscript.js) is the only file you should be minifying and it's also the only file you need (baselib, utils, ast, output, tokenizer are all intermediate files now). RapydScript itself is both a compiler and a minifer, so the easiest way to minify it is to open `src/self.pyj`, remove the line that says `beautify: True` and recompile twice (first time for the compiler to recompile its self-compilation logic and second time to actually apply it). I'll also modify the code in a bit to accept -p option for --self.
