### ISSUE TITLE
Module search path for importable modules

### ISSUE THREAD

**Issue by jpcharlesworth** [atsepkov/RapydScript#111]
We have already discussed this extensively on the Google group but I though it would be useful to record it as an issue so that it doesn't get forgotten,
The original discussion was here https://groups.google.com/forum/#!topic/rapydscript/hK_eBqn5bVk

I thought I had replied to @atsepkov's last post but my reply, to the effect that a relative path would be acceptable, is missing.
I now have a couple of modules which are imported by about 10 applications,  so I have created  a package for them in rapyscript/src/lib. This is fine for the short term but, as we agreed, not a permanent solution. No hurry, just a renewed expression of interest in this topic.

**Comment by kovidgoyal** [comment]
Implemented here: https://github.com/kovidgoyal/rapydscript-ng/commit/318ef1f3bb43242e4bfb515926f97e35f4f5142b

**Comment by atsepkov** [comment]
Thanks, will try to merge it this weekend.

**Comment by jpcharlesworth** [comment]
@kovidgoyal and @atsepkov, thank you both for your response and I look forward to using the new facility in due course.

**Comment by jpcharlesworth** [comment]
This issue was seemingly about to be dealt with back in January but didn't quite make it and is still outstanding. I have made extensive use of imported modules (10 of them), importing them from a package located in RapydScript/src/lib, but it would still be nice to be able to define a location in my project directory from which they could be imported.

**Comment by atsepkov** [comment]
Implemented the fix slightly differently due to differences in compilers, but this should be transparent to the user.

**Comment by kovidgoyal** [comment]
@atsepkov I suggest using the same environment variable name, i.e. RAPYDSCRIPT_IMPORT_PATH rather than RAPYDSCRIPT_PATH. Otherwise it is a needless incompatibility.

**Comment by atsepkov** [comment]
@kovidgoyal Good point, I was going by bash's PATH, node's NODE_PATH and PYTHON_PATH (which I just realized is actually PYTHONPATH). Since it seems customary to omit _IMPORT in these paths, should we do the same for RS?

**Comment by kovidgoyal** [comment]
I deliberately chose to have IMPORT for additional clarity. In the future, there might well be other env vars needed. For example, to specify a location for the pyj-cached files. In any case, rs-ng has been released with RAPYDSCRIPT_IMPORT_PATH for nearly ten months. Changing it now would break existing users code.

**Comment by jpcharlesworth** [comment]
@atsepkov I have it working, thank you. It seems currently to be using RAPYDSCRIPT_PATH but I have defined RAPYDSCRIPT_IMPORT_PATH as well, in case you decide to change it.
