### ISSUE TITLE
"border-color":"#dddddd" resulting compile error

### ISSUE THREAD

**Issue by mardon86** [atsepkov/RapydScript#113]
This code resulting compile error
![rs01](https://cloud.githubusercontent.com/assets/9649930/14577552/d7d809f2-039f-11e6-901f-47aca004214d.png)
ERROR: Unexpected token: punc «}» [test.py:5,0]

These codes perfectly fine
![rs02](https://cloud.githubusercontent.com/assets/9649930/14577576/0125f81e-03a0-11e6-908a-a2e263c29dfa.png)
![rs03](https://cloud.githubusercontent.com/assets/9649930/14577579/082e8a2c-03a0-11e6-92ba-ce881bbc4402.png)

**Comment by atsepkov** [comment]
Which version are you using? Is it from npm or from github? Are you using any special compilation flags? The compilation works fine for me:

test.pyj:

    styles = {
        "border-style":"solid",
        "border-color":"#dddddd",
        "border-width":"1px"
    }

rapydscript -p test.pyj:

    (function(){

        var __name__ = "__main__";


        var styles;
        styles = {
            "border-style": "solid",
            "border-color": "#dddddd",
            "border-width": "1px"
        };
    })();

**Comment by mardon86** [comment]
Im clonning your git (the newest) then create a symlink:
/usr/local/bin/rapydscript -> /media/DATA/GITs/RapydScript/bin/rapydscript
rapydscript 0.3.9
node 5.10.0
just reclone your git but still cannot compile

**Comment by mardon86** [comment]
ERROR: Unexpected token: punc «}» [test.py:5,0]

/media/DATA/GITs/RapydScript/lib/parse.js:148
    throw new JS_Parse_Error(message, line, col, pos, is_eof);
    ^
Error
    at new JS_Parse_Error (/media/DATA/GITs/RapydScript/lib/parse.js:135:18)
    at js_error (/media/DATA/GITs/RapydScript/lib/parse.js:148:11)
    at croak (/media/DATA/GITs/RapydScript/lib/parse.js:788:9)
    at token_error (/media/DATA/GITs/RapydScript/lib/parse.js:793:9)
    at unexpected (/media/DATA/GITs/RapydScript/lib/parse.js:799:9)
    at /media/DATA/GITs/RapydScript/lib/parse.js:1040:17
    at /media/DATA/GITs/RapydScript/lib/parse.js:830:20
    at Object.<anonymous> (/media/DATA/GITs/RapydScript/lib/parse.js:2668:23)
    at Object.parse (/media/DATA/GITs/RapydScript/lib/parse.js:2722:7)
    at parse_file (/media/DATA/GITs/RapydScript/tools/compile.js:42:28)

**Comment by atsepkov** [comment]
Odd, could you attach the actual file causing this error? I wonder if it's some end-of-line or hidden character?

**Comment by mardon86** [comment]
[test.txt](https://github.com/atsepkov/RapydScript/files/222009/test.txt)

**Comment by atsepkov** [comment]
Ah, with your file I can reproduce it. Looks like the indention in your version is different than it was in mine and that is causing the bug.

**Comment by mardon86** [comment]
I changed the indentation using 4 spaces, but the error still occur

**Comment by atsepkov** [comment]
Remove indentation altogether and it will work. It's not a solution, but a temporary workaround until the issue is addressed.

**Comment by mardon86** [comment]
Ok. thanks @atsepkov
