### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by FeralBytes** [atsepkov/RapydScript#115]
I would like to contribute some improvements to your documentation; but it is not included in this repository; so where is it located. I know there is the website but I would like the source of the documentation in order to improve it. I feel that there should be a quick newbie introduction because there were several initial concepts that did not make sense to me and it delayed me being able to use Rapydscript for the first day. In the mean time I will start working on a patch to the README.md.
Thank you for this great project.

**Comment by atsepkov** [comment]
Do you mean the different pages on rapydscript.com? Those are portions of README.md that I have pulled out and eventually turned into their own webpages, powered by wordpress. Unfortunately these aren't in the repo, although perhaps they should be (I haven't really thought of that). If you're interested in contributing, I'm open to granting you editor access.

**Comment by FeralBytes** [comment]
Yes I was referring to the pages on rapydscript.com; I did realize that they are taken from the README.md. I am definitely interested in contributing to your project; I think it is very empowering to be able to do JavaScript in a language that much more resembles Python. I will be working on some of the proposed changes over the next week and I will submit them in a independent PR's for your review.

**Comment by FeralBytes** [comment]
@atsepkov Are you willing to pull down the documents that you currently have on rapydscript.com to start creating a docs folder; or would you like me to do it? I still need to make my changes to the README.md but will be on to creating a docs section in the repo next.

**Comment by atsepkov** [comment]
@FeralBytes I don't see a problem with that, aside from duplication (between README.md and the individual wordpress pages) that may become a pain to maintain. Alternatively, I could also grant you editor access to the website so you can edit the pages directly. Let me know which you'd prefer.

**Comment by FeralBytes** [comment]
OK if you give me editor access I will pull down the pages and build the "docs/" directory; even though it will cause some duplication. I am pretty sure it will not be too challenging to keep them in sync.

**Comment by FeralBytes** [comment]
Please review #116

**Comment by atsepkov** [comment]
Merged
