### ISSUE TITLE
Failed to update scope on method assignment

### ISSUE THREAD

**Issue by mozbugbox** [atsepkov/RapydScript#117]
When a class method is assigned to a variable, calling the variable will lose the `self` scrope.

```py
# Failed to update scope on method assignment
class A:
    def __init__(self):
        self.value = 3
    def foo(self):
        print(self.value)
    def bar(self):
        foo = self.foo
        foo()

a = A()
a.bar()
```

Calling `foo()` in `bar()` will print `undefined`.

**Comment by atsepkov** [comment]
This is a result of how JavaScript handles (or rather doesn't) binding. If I was to automatically bind functions to the object, the code would be slow an inefficient (it would effectively create unique copies of each function for the object). In Python, the method is always bound to the instance, in JavaScript it never is, unless you bind it explicitly.

See the following section of the README for a more thorough explanation of this: https://github.com/atsepkov/RapydScript#method-binding

**Comment by kovidgoyal** [comment]
Note that in rapydscript-ng you can just do 

from __python__ import bound_methods

to have all methods auto-bound in that scope.

**Comment by atsepkov** [comment]
@kovidgoyal is the scope limited to the module or does it leak into imported modules too?

**Comment by kovidgoyal** [comment]
It is limited to the current scope, which means the current class if it is in a class declaration or the current module if it is at module level. See the writeup on scoped flags in the rs-ng readme

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/rapydscript-ng#method-binding
