### ISSUE TITLE
List comprehension containing an enumeration does not compile correctly

### ISSUE THREAD

**Issue by jpcharlesworth** [atsepkov/RapydScript#119]
I have a list of objects, each of which has the same set of attributes. I want to construct a list containing the indices in the original list of those objects for which a specific attribute has a given value.

data is the list of objects
'SailNo' is the specific attribute and sailNo is the given value.

I create a list comprehension thus:

    matches = [i for i, rec in enumerate(data) if rec['SailNo'] is sailNo]

That compiles to

                  matches = (function() {
                    var ՐՏ_Iter = ՐՏ_Iterable(enumerate(data)), ՐՏ_Result = [], i, rec;
                    for (var ՐՏ_Index = 0; ՐՏ_Index < ՐՏ_Iter.length; ՐՏ_Index++) {
                        ՐՏ_Unpack = ՐՏ_Iter[ՐՏ_Index];
                        i = ՐՏ_Unpack[0];
                        rec = ՐՏ_Unpack[1];
                        if (rec["SailNo"] === sailNo) {
                            ՐՏ_Result.push(i);
                        }
                    }
                    return ՐՏ_Result;
                })();

When executed it produces this error:
Uncaught ReferenceError: ՐՏ_Unpack is not defined (at the 4th line of the code snippet above)

If I insert a declaration of  ՐՏ_Unpack in the var line of the function, the code works.

The RapydScript source used to compile correctly but failed to do so after a recompile in early August. It probably hadn't been recompiled for several months before that.

**Comment by atsepkov** [comment]
Are you using the latest version, this sounds like #110 , which I fixed last week. I'll push it to npm too just in case.

**Comment by jpcharlesworth** [comment]
No I wasn't using the latest version but I have now updated to your latest commit 48d3af6 and I see that  the 4th javascript line of my example above has now become

        var ՐՏ_Unpack = ՐՏ_Iter[ՐՏ_Index];

which does cure the problem. Thanks.
