### ISSUE TITLE
refactor ast.pyj into classes

### ISSUE THREAD

**Issue by atsepkov** [atsepkov/RapydScript#120]
The logic in ast.pyj is a patched variation of uglify.js logic, which, compared to the rest of RapydScript, is starting to look quite ugly. I've glanced at it a couple times, but refactoring it isn't as straight-forward as I first expected. With that said, I still would like to rewrite the module such that every AST object is a class inheriting from AST_Node. If done correctly, this should be mostly transparent to other modules. Unfortunately in its current state the ast module uses quite a few anti-patterns that need to be resolved.

**Comment by kovidgoyal** [comment]
Note that I looked at this briefly, but concluded that the performance hit is too large (classes for some reason turned out to be a lot slower that plain JS objects -- I did not have the time then to look into exactly why).

**Comment by atsepkov** [comment]
Good to know. Was it an order of magnitude performance impact or just noticeable overhead? I'm surprised by this seeing how DEFNODE is basically an ugly version of a class factory. I don't do anything fancy in my classes either, just use the prototype, which DEFNODE relies on as well. Perhaps `Object.create` is adding this overhead, I'll run some tests.

**Comment by kovidgoyal** [comment]
I'm afraid I dont remember the exact numbers (should have kept notes). It certainly was not an order of magnitude, but given the amount of grunt work needed to complete the translation combined witht he performance decrease it was enough to dissuade me from trying.

**Comment by kovidgoyal** [comment]
Also note that rs-ng classes do a bit more work than in the original RS, because they have to support multiple inheritance and a couple of other bells and whistles.

**Comment by kovidgoyal** [comment]
FYI, I realized that the overhead from multiple inheritance can be removed by simply using a custom function instead of isinstance, since we know that the compiler does not use multiple inheritance. With that, there is no performance impact.

**Comment by atsepkov** [comment]
Addressed by a8ba8a08a0aa32a0026c02d69553404345c37b37.
