### ISSUE TITLE
Problem compiling code

### ISSUE THREAD

**Issue by jpcharlesworth** [atsepkov/RapydScript#123]
I have the current github master version of RapydScript installed and generally working very well but I have one file which fails to compile with the following error trace:

 C:\Users\Phil\RapydScript\lib\rapydscript.js:6179
                if (right[0] === "[") {

                         ^

TypeError: Cannot read property '0' of null

    at validateBinary (C:\Users\Phil\RapydScript\lib\rapydscript.js:6179:26)
    at expr_op (C:\Users\Phil\RapydScript\lib\rapydscript.js:6293:21)
    at expr_ops (C:\Users\Phil\RapydScript\lib\rapydscript.js:6308:20)
    at maybe_conditional (C:\Users\Phil\RapydScript\lib\rapydscript.js:6313:20)
    at maybe_assign (C:\Users\Phil\RapydScript\lib\rapydscript.js:6354:20)
    at maybe_assign (C:\Users\Phil\RapydScript\lib\rapydscript.js:6362:29)
    at expression (C:\Users\Phil\RapydScript\lib\rapydscript.js:6382:20)
    at simple_statement (C:\Users\Phil\RapydScript\lib\rapydscript.js:4563:19)
    at statement (C:\Users\Phil\RapydScript\lib\rapydscript.js:4410:88)
    at C:\Users\Phil\RapydScript\lib\rapydscript.js:4293:24

The file compiles with version 0.5.20 but fails with this error on all versions from 0.5.21.

I hesitate to attach the file as it is 1600 lines but will do so if you need it.

**Comment by atsepkov** [comment]
Could you get me an example of code that triggers this error? The logic you're referencing validates type safety and by the time it hits that block `right` should always be a string. If that's not happening something earlier on went wrong and I'd need to trace it back.

**Comment by jpcharlesworth** [comment]
I've tracked down the construct that triggers the error. This little piece of code is sufficient to show it.

   def showTabContent():
       table = None
       if table:
           print('Loading ' + table)

I'm compiling with the flags -b -p -m but I doubt that any of those make any difference.

**Comment by atsepkov** [comment]
Added proper check to raise a type error here. However, the compiler will ignore the fact that you're inside a conditional that will always evaluate to false because the last assigned value it sees to table is None. While I need to check that I'm properly handling branches in the code for type resolution, in this case I'm leaning towards keeping the error about incompatible binary addition.

**Comment by jpcharlesworth** [comment]
Here is a more realistic sample with some of the detail filled in.

    def showTabContent(self, title):
        if title is 'Starts':
            table = 'Starts'
            # do some stuff
        elif title is 'Times':
            table = 'Times'
            # do some stuff
        elif title is 'Codes':
            table = 'Codes'
            # do some stuff
        elif title = 'Analysis':
            table = None
            # do some stuff
        elif title is 'Boats':
            # do some stuff
            return
        else:
            return
        # do some stuff
        if table:
            print('Loading ' + table)
            # load the table

It's a moot point whether this should throw a compiile error because the logic is quite clear and it's not breaking any rules and it would execute correctly. Interestingly, if I replace `table = None` by `table = False`, it compiles OK, as of course it does if I use `table = ''`.

It would be perfectly reasonable for the linter to issue a warning  about this kind of thing - that's its job - but I'm not entirely convinced that the compiler should be going so far as to refuse to compile the code. At least, now, it tells you what is worrying it and you have an opportunity to fix it; but too many such 'errors' might get a bit irritating. If the compiler could just give a warning and then continue to compile, that would be better, but might be hard to implement.

Anyway, thanks for the fix you have implemented, I now have code that executes again and if I trigger the same problem again, I will know what to do about it.

**Comment by atsepkov** [comment]
That's because concatenation is a valid expression on Number, String, and Boolean. The reason I didn't add None to the list is to prevent the nuisance cases like this:

```
n = undefined
p = "I have " + n + " books" # "I have undefined books"
```

**Comment by jpcharlesworth** [comment]
Thank you for the detailed explanation and I am happy to live with the current situation until you have time to action your proposals above. I agree that the current issue should now be closed and I will do that.
