### ISSUE TITLE
Problem with typeof

### ISSUE THREAD

**Issue by jpcharlesworth** [atsepkov/RapydScript#125]
If I compile this code fragment with any commit later than 4ce563 version 0.5.47

     if typeof val is 'undefined':
          val = 2
     else:
         print(val)

I get the following error message 
ERROR: Unexpected token: punc «:» [test.py:3,4]

**Comment by atsepkov** [comment]
`typeof` has been removed from the language in favor of the more useful `type()` function, which returns actual type rather than `object` , however you can still use `JS('typeof val')`. You can also use `type(val) is 'Undefined'`.

**Comment by jpcharlesworth** [comment]
Fine; I like that.
And instanceof is replaced by isinstance()?

**Comment by atsepkov** [comment]
Yep, isinstance() actually compiles to instanceof directly, since instanceof works as advertised unlike typeof. By the way, note that the first letter of type is now capitalized.

**Comment by jpcharlesworth** [comment]
I am still puzzled by this, with reference to your comment three days ago.

The line `  if(type(process) is 'Undefined'):`
compiles to         if (ՐՏ_type(process) === "Undefined") {

If I execute it in a page served from localhost on Chrome v54, I get
Uncaught Reference Error: process is not defined.

**Comment by atsepkov** [comment]
So this is actually strict mode of JavaScript complaining about `process` before I even have a chance to run any logic on it, but it seems that `typeof` operator is special in that it actually uses something akin to a string-eval. You can test it yourself with vanilla JavaScript:

    foo; // undefined error
    typeof foo; // works

    // also undefined error
    function bar(a) { return typeof a; }
    bar(foo);

    // also undefined error (even though the right hand side should be ignored)
    typeof foo && bar(foo);

Based on these tests, it seems like `typeof foo` under the hood does something like this instead:

    typeof window['foo'] (in browser)
    typeof global['foo'] (in node)

You could use `JS('typeof foo')` to get yourself this functionality or use the Python's approach of wrapping it in a try/catch block.

p.s. I did fix another (similar) bug in type and pushed the change in, so while it's not what you got bitten by I suggest you update for proper undefined handling of cases like `a.undef`.
