### ISSUE TITLE
static methods within declaration of class aren't marked static

### ISSUE THREAD

**Issue by atsepkov** [atsepkov/RapydScript#128]
Example:

```
class Test:
    def foo(self):
        Test.me()
    @staticmethod
    def me():
        pass
```

The issue is with the fact that class object does not yet exist when the call to the method is triggered. Potential fixes:
- delay the static check until output
- do a second pass through the code
- check if the object name we're referencing matches the scope name of the class and delay the check until the end of the declaration
- set up a promise-like evaluation for such logic

**Comment by valq7711** [comment]
There is another bug like this:
```
@external
class Foo:
   @staticmethod
    def set():  # - OK
        pass  
    @staticmethod
    def delete():  # - will be  Foo.prototype.delete.call()
        pass  
```
This occurs when the name of the method is any  JS-keyword

**Comment by valq7711** [comment]
fixed
