### ISSUE TITLE
[Rapydscript on web] import implementation

### ISSUE THREAD

**Issue by mardon86** [atsepkov/RapydScript#134]
Hi, @atsepkov  i'm developing a simple rapydscript repl on web. I think this might be a good start to become a larger project. Please have a look [https://mardon86.github.io/RapydScript_REPL/](https://mardon86.github.io/RapydScript_REPL/). The repl itself is written in rapydscript (look at the source code). Any suggestion and advice are welcomed.

The repl takes rapydscript.js directly from your github repo (user raw content). Then store it into localstorage, so that there's no need to fetch the rapydscript.js again at next visit if the rapydscript version is not changed (taken from package.json). But even so i think  its a good idea that you also release the minified version every time you change your code to reduce the bandwidth usage.

I also implemented import functionality using a function to get .pyj file from user input. It works fine so far, but i'm not 100% sure if i did it right. Maybe you can take a look into the my implementation and correct me if i did it wrong. However i prefer to use the pythonic import statement syntax instead of a function implementation. I find that the rapydscript import implementation only works on node environment. So I think its a good idea to create pythonic import implementation to get rs file from the server or from user input.

thx.

**Comment by kovidgoyal** [comment]
You know there is already a web REPL here, right: https://kovidgoyal.github.io/rapydscript/repl/

It even has popup completion :)

**Comment by mardon86** [comment]
Ooh yeah,, Hi @kovid, so i'm reinventing the wheel then,, :D
Actually i like your rapydscript-ng, it more close to python. But i dont know why it doesn't work on my android browser, even i using kitkat (i think this version is still one of the mainstream version of android phone these days). If you remember i posted an issue about this. So then i must use it on firefox or chrome to make it works. Maybe it because of the eval thing i dont know. So i'm using the original rapydscript to be embedded on web page, besides the size is much smaller than rs-ng :)

**Comment by kovidgoyal** [comment]
You are using the ES 5 compiler option as documented here: https://github.com/kovidgoyal/rapydscript-ng#embedding-the-rapydscript-compiler-in-your-webpage (see the first note). IIRC that was added sometime after you reported your issue.

**Comment by icarito** [comment]
Hi,
Maybe its a good moment to share [*rapydscriptify*](https://www.npmjs.com/package/rapydscriptify) which is a browserify transform that I used to do this at precompilation stage. Here's a template I'm working on that uses it: https://somosazucar.github.io/python-web/

What's cool about it is that it's possible to use live module reloading.
I've set it up to compile both using Transcrypt and Rapydscript.

There are quirks that I tried to abstract away. Hopefully it can be useful!

**Comment by icarito** [comment]
To clarify, *rapydscriptify* is a very simple package for browserify. Only the mentioned template uses Transcrypt.

**Comment by valq7711** [comment]
Now, there is `lib/rapydscript_web.js` that is AMD compliant.
So, in the browser you can:
```python

# required to mimic node.fs behavior
class Not_found(Error):
    def __init__(self):
        self.code = 'ENOENT'  

def file_reader(path_to_file):
    ... # get content of file
    if not_found:
        raise Not_found()
    return file_content

options = {
     basedir: '/some/dir',
     readfile: file_reader,
     es6: True,
     beautify: True,
     import_dirs: ['/some/path', '/another/path']
}
output =  rapydscript.compile(code_string, options)

# to compile something simple using default options  
output =  rapydscript.compile('def foo():\n    pass\n', {}) 
```
