### ISSUE TITLE
cant run on OSX 

### ISSUE THREAD

**Issue by pepsiquantum** [atsepkov/RapydScript#139]
Installed Versions
nodejs: v6.9.1
npm: 3.10.8
rapydscript@0.5.55

when I try to run rapydscript from the command line, I get the following error. 

-bash: rapydscript: command not found

any help would be appreciated

**Comment by atsepkov** [comment]
I run RapydScript on OSX myself, so I'm 100% sure OSX is not the problem. How did you install it, what were the exact commands you used?

**Comment by atsepkov** [comment]
No response, closing issue.
