### ISSUE TITLE
Class variables are isolated from each other during the creation of the class

### ISSUE THREAD

**Issue by valq7711** [atsepkov/RapydScript#141]
```
class SomeA:
      a= 1
      b= a+2  # or  SomeA.prototype.a + 2    - doesn't matter
```
will compile to

```
var SomeA = (ՐՏ_1 = function SomeA() {
    }, Object.defineProperties(ՐՏ_1.prototype, {
        a: {
            enumerable: true, 
            writable: true, 
            value: 1        },
        b: {
            enumerable: true, 
            writable: true, 
            value: a + 2        }
    }), ՐՏ_1);
```
``` value:  a+2 ``` - will cause  ReferenceError

Expected something like this:
```
var SomeA = (ՐՏ_1 = function SomeA() {
    }, (function(){
       var a= 1;
       var b= a+2;
        Object.defineProperties(ՐՏ_1.prototype, {
              a: {
                   enumerable: true, 
                   writable: true, 
                   value: a        },
              b: {
                  enumerable: true, 
                  writable: true, 
                  value: b        }
        });
})(), ՐՏ_1);
```

**Comment by atsepkov** [comment]
Your alternative approach looks good to me. Unfortunately I'm tied up with another project (a startup) about 14 hours per day and won't have the ability to make this change any time soon, but if you want to make a pull request yourself with the change, I'll approve it.

**Comment by valq7711** [comment]
done

**Comment by valq7711** [comment]
done  Es5 only

**Comment by atsepkov** [comment]
I've merged the change, but fixing this in ES6 version is actually more important to the language than ES5, since I'm planning to drop support for ES5 within a year in favor of simplifying the compiler and letting tools like Babel handle older versions.
