### ISSUE TITLE
ES6 classes js-native implementation is not as flexible as Rapydscript es5

### ISSUE THREAD

**Issue by valq7711** [atsepkov/RapydScript#151]
With  es6 you can't do any pre-inits in the  `__init__`-call of the derived class   (like `self.some = ...`) before `super()`-call, because `self ` (this) doesn't yet exist!  As I see, it's better to place all more-less complex init-logic in the separated function(s), but not  in the ` __init__`. Pythonic definition like `def __init__(self):` for derived classes become unclear.

**Comment by atsepkov** [comment]
Yes, it's a similar issue with class variables in ES6. ES6 classes do not allow clean declaration for them at the time of class creation so I had to use a hack to append them after the fact (haven't looked at that logic in a while so I'm rusty on it).

I'm not sure what the best approach is, to throw an error in RapydScript, or try to work around it with additional logic. `__init__` being separate from the constructor in RS is another hack that sometimes works well and in other cases (i.e. passing arguments via spread operator) creates a ton of unnecessary complexity for the compiler to deal with.

If I understand you correctly, you're saying that RS lost some functionality it has in ES5 by embracing ES6 class?

**Comment by valq7711** [comment]
Yes, I mourn a little.... Talking about separated init-logic I don't mean refactoring the compiler, just code tricks. I remember that RS isn't Python, but something that makes JS-coding easier and clear.
P.S. Now,  you can  accept pull request #146 - all tests should be passed

**Comment by amigrave** [comment]
I use RS in a project running on non browser javascript VM and I remember using tricky inheritance in my models.
I'll have a check if it still works with `--es6` + babel...
Will report here.
