### ISSUE TITLE
RapydScript GitHub page links to "expired" rapydscript.com

### ISSUE THREAD

**Issue by ssb22** [atsepkov/RapydScript#161]
RapydScript GitHub page links to rapydscript.com, but going there gives the message "This Domain Name Has Expired" with links to renewal instructions and third-party advertising.

The last good version in Internet Archive appears to be https://web.archive.org/web/20170627232519/http://www.rapydscript.com/ if that's any use.

**Comment by atsepkov** [comment]
Thanks, reactivated the domain.
