### ISSUE TITLE
Function is not substituted when passed as an object

### ISSUE THREAD

**Issue by bazitur** [atsepkov/RapydScript#162]
I've tried this small snippet:
```python
def foo(*args):
    print(map(type, args))
foo(1, 2, "spam", None)
```
And here is what I get:
```js
function foo() {
    var args = [].slice.call(arguments, 0);
    ՐՏ_print(map(type, args));
}
```
As you can see, function `type` was not replaced.

**Comment by atsepkov** [comment]
What should the function be substituted with? I'm confused. `type` has no significance in RapydScript, in the code above it's just an undeclared variable. `map` function is a wrapper around `Array.prototype.map` and should work the same way as Python's map if `type` is an actual function.

**Comment by bazitur** [comment]
Well, if I run
```py
print(type(1))
```
I get this:
```js
ՐՏ_print(ՐՏ_type(1));
```
Which works perfectly.

**Comment by atsepkov** [comment]
Oh, now I remember. `type` was my wrapper around `typeof` to make it more useful. Sorry, haven't worked with this recently. So in this case, the way I identify that the variable is a function, is by seeing the parentheses. Trying to rewrite type into RS_type without being sure it's the same function could introduce additional problems. In your case an easy workaround around be to wrap it in an extra function:

    def foo(*args):
        print(map(def(a): type(a);, args))
