### ISSUE TITLE
Is there a way to suppress newline in print statement?

### ISSUE THREAD

**Issue by jonschull** [atsepkov/RapydScript#166]
Greetings, 

Is there a way to suppress newline in print statements?

In python 3 you would use the end='' keyword

`print('no newline', end='')`

**Comment by atsepkov** [comment]
print() leverages console.log(), you can find the actual implementation in src/baselib.pyj. Unless console.log allows disabling the newline, or you find another way to print to screen, I think the answer is going to be "no", but feel free to look at the baselib file above to see if it's something simple I may have missed.
