### ISSUE TITLE
Website parked?

### ISSUE THREAD

**Issue by jakirkham** [atsepkov/RapydScript#176]
<img width="1552" alt="screen shot 2018-08-04 at 17 27 52" src="https://user-images.githubusercontent.com/3019665/43680566-c45d5f64-980b-11e8-9421-ae74d42327ef.png">

**Comment by atsepkov** [comment]
The website has expired and seems to have been bought by an unrelated 3rd party. It no longer has any relevance to the project. I have removed references to it, if you find other references I forgot, please let me know.

The mailing list (http://groups.google.com/group/rapydscript) and facebook page (https://www.facebook.com/rapydscript/) still belong to this project. Thanks.

**Comment by Tset-Noitamotua** [comment]
more references --> http://slides.com/atsepkov/rapydscript-3#/14

**Comment by Tset-Noitamotua** [comment]
suggestion: host a static site as Github Pages. Costs nothing, enhances find-ability and ranking on Google.

**Comment by Tset-Noitamotua** [comment]
https://pages.github.com/

**Comment by atsepkov** [comment]
Is this different from what I already have? http://atsepkov.github.io/RapydScript

**Comment by Tset-Noitamotua** [comment]
nope, that's fine ... haven't seen it :see_no_evil:
