### ISSUE TITLE
website www.pyjeon.com hacked / parked?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [atsepkov/RapydScript#191]
whats up with www.pyjeon.com? does it relate to this project? it's parked or hacked or whatever.

Are u interested in getting a sponsored custom domain like .org or .dev etc. for this project?

**Comment by Tset-Noitamotua** [comment]
btw. the links on your [twitter account](https://twitter.com/ATsepkov) seem to be outdated as well :grimacing:

**Comment by atsepkov** [comment]
It was an old website I used for my projects back in 2011. As for RapydScript, I no longer have time to actively maintain it but I still use this language for scripting. IMO, the best direction for RapydScript that I'd prefer:
- standardize ES6 mode, remove ES5 mode (to simplify code)
- improve type tracking of variables (I have a separate project for this which uses promises to resolve possible types for each variable that I want to integrate RapydScript with, but latest code is not yet on github)
- drop some pythonisms in favor of modern JS to make code clearer (i.e. replace splat `*` with more intuitive `...`)

So yes, a website name may be nice, but what would be even nicer is more contributors to the project.

**Comment by Tset-Noitamotua** [comment]
more popularity (e.g. through a nice website) would bring more contributors :)

**Comment by atsepkov** [comment]
That's what rapydscript.com was, like I said I no longer have time to maintain it.
