### ISSUE TITLE
Question: What do you think about these comments Guido v. R. once made?

### ISSUE THREAD

**Issue by Tset-Noitamotua** [atsepkov/RapydScript#192]
Hey, I'd really like to know your thoughts about what Guido. v. R. answered in the past to questions about Python support in browsers :nerd_face: 

- [Q&A: Guido van Rossum on Python's next steps](http://www.infoworld.com/article/3078633/application-development/qa-guido-van-rossum-on-pythons-next-steps.html) (June 2016)
  > **InfoWorld:** Will Python ever have the kind of role in the browser that JavaScript has, or is that not in the cards?
  > **Guido Van Rossum:** There are better goals in life. (...)
  >
  > **InfoWorld:** While we're talking about JavaScript, what is your impression of WebAssembly?
  > **Van Rossum:** This would actually perhaps make running Python in the browser more possible.
- [Interview with Guido van Rossum](https://developers.slashdot.org/story/13/08/25/2115204/interviews-guidovan-rossum-answers-your-questions) (August 2013)
  > **Question:** ... is it time to give up on python in the browser?
  > **Guido Van Rossum:** I gave up on it in 1995, so yes. And please don't try to compile Python to JavaScript. The semantics are so different that you end up writing most of a Python runtime in JavaScript, which slows things down too much. (CoffeScript's strength is that it is designed to map cleanly to JavaScript, and the two are now co-evolving to make the mapping even cleaner.)

**Comment by atsepkov** [comment]
Not sure what needs commenting here. I agree with Guido's comments, these questions have been brought up before, and are part of the reason this project exists. To summarize:
- If you want to write for the browser, use a platform that embraces JavaScript.
- WebAssembly will provide more opportunity for new languages.
- Python in the browser (Skulpt, Brython, Pyjamas, etc.) can't compete with native JavaScript, platforms that embrace JavaScript (CoffeeScript, TypeScript, RapydScript) can.

Please move questions/discussions to the mailing list: http://groups.google.com/group/rapydscript
