### ISSUE TITLE
Why not support in-browser compiler?

### ISSUE THREAD

**Issue by 625781186** [atsepkov/RapydScript#215]
https://github.com/adousen/RapydScript-pyjTransformer 

The project is no longer maintained.

Is it possible to provide a way to import directly without relying on Nodejs?

`    <script src="https://cdn..../rapydScript.min.js"></script>
`

**Comment by valq7711** [comment]
There is rapydscript_web.js in the lib folder - this is what you need

**Comment by 625781186** [comment]
> There is rapydscript_web.js in the lib folder - this is what you need

OK , thanks.
I want to add this ntroduction to  `README.md` .
