### ISSUE TITLE
fstring support.

### ISSUE THREAD

**Issue by 625781186** [atsepkov/RapydScript#235]
error : 
![image](https://user-images.githubusercontent.com/30521429/85307738-da855080-b4e2-11ea-81c3-3a47919cb394.png)

right:

![image](https://user-images.githubusercontent.com/30521429/85307601-ae69cf80-b4e2-11ea-86c4-43e69b39cb54.png)

py ftsing  use `{}` , but  js string  use `${}`,

**Comment by valq7711** [comment]
Hi, use `f'${}'`
https://github.com/atsepkov/RapydScript/blob/master/README.md#es6-features
