### ISSUE TITLE
How to keep  all comments

### ISSUE THREAD

**Issue by 625781186** [atsepkov/RapydScript#236]
![image](https://user-images.githubusercontent.com/30521429/85355883-24e8ea80-b540-11ea-9bb4-6db240fb838d.png)

I use command `rapydscript F:\dida\JG360web\apps\conftest_api.py -6 -p -m -b  --comments=all`, but can't save comments.

![image](https://user-images.githubusercontent.com/30521429/85355979-595ca680-b540-11ea-9367-553380592485.png)

**Comment by valq7711** [comment]
should be fixed now

**Comment by 625781186** [comment]
> should be fixed now

Not be fixed .  still not working.

**Comment by 625781186** [comment]
> should be fixed now

Not be fixed. Still not working.

```
F:\dida\JG360web>uglifyjs -V
uglify-js 3.9.3
```
```
F:\dida\JG360web>rapydscript -V
rapydscript 0.5.62
```

**Comment by valq7711** [comment]
I fixed only source - try recompile `bin/rapydscript --self`

**Comment by 625781186** [comment]
> I fixed only source - try recompile `bin/rapydscript --self`

![image](https://user-images.githubusercontent.com/30521429/89805300-04183b00-db68-11ea-9dd2-29b722c3d76d.png)

Hi , I tried, it possible to keep the header comments ?

**Comment by 625781186** [comment]
@valq7711 https://github.com/atsepkov/RapydScript/issues/236#issuecomment-671451721

**Comment by valq7711** [comment]
Sorry, have no time, fix asap

**Comment by valq7711** [comment]
@625781186 try now

**Comment by 625781186** [comment]
> @625781186 try now

Very nice , Thank you very much !
