### ISSUE TITLE
Can't find python module that is installed and available?

### ISSUE THREAD

**Issue by dachshund-digital** [atsepkov/RapydScript#237]
Can't find python module that is installed and available?

` sudo ./rapydscript /root/SensorSI7021Class.py

/home/pi/.node-red/node_modules/rapydscript/lib/rapydscript.js:5306
                throw new ImportError("Failed Import: '" + key + "' module doesn't exist in any of the import directories: " + import_dirs.join(", "), options.filename);
                ^
[ImportError: Failed Import: 'time' module doesn't exist in any of the import directories: /root, /home/pi/.node-red/node_modules/rapydscript/src/lib] {
  filename: '/root/SensorSI7021Class.py',
  readfile_error: undefined
}
pi@pi4modelb0:~/.node-red/node_modules/rapydscript/bin $ python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import time
>>>
`

**Comment by atsepkov** [comment]
See the first sentence of the README file. This isn't a Python compiler, it's a JS compiler with Python syntax, your `.py` files are ignored. If you want a Python-like `time` module, you'll need to write a wrapper around JS `Date` object similar to the ones in https://github.com/atsepkov/RapydScript/tree/master/src/lib directory (i.e. `re.pyj` to simulate `re` module), or you can use `Date` directly.
