### ISSUE TITLE
Python docstrings

### ISSUE THREAD

**Issue by jpcharlesworth** [atsepkov/RapydScript#32]
I have found that some RapydScript code which I have not modified for a while no longer compiles. I eventually tracked the problem down to comments like this:

""" This is a Python docstring """
 This throws an exception at parse.js line 578
TypeError: cannot read property 'length' of null

The problem seems to be having both triple quotes on the same line.

I am pretty sure that this problem has arisen relatively recently, otherwise I would have already been aware of it.

**Comment by atsepkov** [comment]
Good catch, it was caused by a naive assumption that docstrings are several lines long.
