### ISSUE TITLE
Properties ("Getters and Setters")

### ISSUE THREAD

**Issue by valmynd** [atsepkov/RapydScript#4]
Python Properties and JavaScript Getters and Setters have much in common: They mimic attribute access when in reality a getter and setter method is called. Just the Syntax is different. I made a little example to see how far this works with RapydScript:

``` python
class Element:
    def __init__(self, tag, attrib):
        self._children = []
        # variant 1: this is be the javascript way of declaring getters
        # see http://stackoverflow.com/a/813332/852994
        get length() = def(self):
            return len(self._children)

    # variant 2:  pythons native property-getters and -setters would make
    # sense to be translated to js-getter and -setters, see variant 1
    @property
    def length(self):
        return len(self._children)

    # varuant 3: while python has obj.__len__(), javascript has obj.length
    # thus it would make sense to replace the following by variant 2
    def __len__(self):
        return len(self._children)
```

Sadly, none of those variants above is properly translated with the current version of RapydScript:

``` javascript
Element = function(tag, attrib){
    var self = this;
    self._children = [];
    get;
    length() = function(self) {
        return len(self._children);
    };
};
Element.prototype.length = function(){
    var self = this;
    return len(self._children);
};
Element.prototype.__len__ = function(){
    var self = this;
    return len(self._children);
};
```

What I would wish for would be, that property decorators translate into javascript getters and setters and that magic functions like __str__(), __len__() etc. would be mapped to their javascript counterparts (in case of __str__() that would be toString()) maybe leveraging those properties thus making it easier to reuse and mix client code and backend code.

Thanks a lot for developing RapydScript btw.!

**Comment by atsepkov** [comment]
I wish I had more time to look at this, will leave alone for now but would appreciate if someone else could look into tackling this to handle these in pythonic way. Another good alternative for creating these is defineProperty function:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

**Comment by kovidgoyal** [comment]
Implemented in my fork: https://github.com/kovidgoyal/rapydscript-ng/commit/e9a6bd3f1ada5b5e52d3f2ee222eea615bf20296

**Comment by atsepkov** [comment]
Implemented in ES6 mode with standard ES6 syntax (this is closest to variant 1 described above):

class Element:
    def __init__(self, tag, attrib):
        self._children = []

    get length() = def(self):
        return len(self._children)

Still on the fence about implementing the Python syntax. While this is not standard Python approach (doesn't look like Python community is fond of them: http://stackoverflow.com/questions/2627002/whats-the-pythonic-way-to-use-getters-and-setters), the `get/set` of ES6 seem to complement `def` better.
