### ISSUE TITLE
add linter stage in compilation

### ISSUE THREAD

**Issue by atsepkov** [atsepkov/RapydScript#44]
In addition to optimizer (https://github.com/atsepkov/RapydScript/issues/39), RapydScript could use a linter. There are certain design patterns that are harmful in JS. Sometimes it's easy to detect when developer is doing something funky by looking at the code, even for an automated tool. Yet we do not want to cause an error in these cases due to a small possibility of false positive. For cases like this, I'd like to add a linter stage, that will warn about potential bugs in the code but can easily be silenced by the developer. For example, the following pattern is 90% likely to be a bug (regular equality check on array) and can easily be warned about by the linter:

    def scope():
        a = [...]
        ... # no assignment to a here
        if a == ...:
           ...

Similarly:

    def scope():
        a = [...] # explicitly defined length (n)
        ... # number of push/append operations can be bound to m
        a[k] # use of a[k] for purposes other than assignment where k > m+n

In fact, in the above scenario, the assignment to a[k] may itself be flagged as bad and a.push() be preferred due to its inability to push elements out of order, in which case the following anti-pattern would also be flagged against by the linter:

    def scope():
        a = [...] # explicitly defined length (n)
        ... # number of push/append operations can be bound to m
        a[k] = ... # where k > m+n

Likewise, the following can be warned against in case developer meant to do a check against undefined:

    if a != None:
        ...

Additionally patterns like this, which would result in number concatenation rather than addition and can easily be silenced via the use of str():

    'string' + 1 + 2

Also, the following pattern may be indicative that the user did something they did not intend to do:

    def func(..., a, **kw):
        ... # do something with a

Because kw has been defined but unused (this may also apply to other arguments for the function), suggesting that user either mistakenly assumed that `a` will alias `kw.a` like in Python without `@kwargs` decorator or did not intend kw to be in the input.

Another anti-pattern:

    def scope():
        a = [...]
        ...
        a['string'] = ... # using array as a dict

Yet another bug that linter can catch:

    def scope():
        a = [...]
        ...
        a + ... # concatenating arrays in JS will stringify them

The above can be extended to functions/objects as well, really `+` only makes sense on strings/numbers in JS, and once the linter is sure the object is neither, it can safely raise a red flag. `-` only makes sense on numbers.

A more dangerous, yet useful feature for the linter could be attempting to match up function calls against signature when possible (duck typing makes this possible, but in some cases you can be pretty certain which call is being referred to). If such match is made, the linter can do additional gut checks:

- does function even exist?
- does the number of arguments being passed match? Every optional argument must have a default specified
- do argument types match when type can be reasonably inferred? For this, the linter can make a sane assumption that `None` is ok substitute for any type, but strings/numbers/arrays/hashes/functions are not interchangeable (this may also be an optional flag for more advanced linting or kick in when user defines type annotations via Python-3 style)
- does return signature match?

The above check could be problematic if multiple functions by same name exist within multiple classes, but many can be further remedied/detected by assuming that whatever type was first assigned to a variable will be exclusively used by it.

One potential technique for telling the linter to ignore a certain problem could be a comment:

    a['badkey'] = ... # NOLINT: this is intentional

**Comment by atsepkov** [comment]
linter is now part of the compiler, however, it still doesn't address the above cases

**Comment by hartsantler** [comment]
maybe the linter could also suggest workarounds for some cases like checking if two arrays are equal.
```python
a = [1,2]
b = [1,2]
if a == b:
   ...
```
the linter could say, arrays can not be tested for equality like that, and that this could be used as an explicit workaround:
```python
if JSON.stringify(a) == JSON.stringify(b):
   ...
```
