### ISSUE TITLE
Support for array declaration via *size

### ISSUE THREAD

**Issue by atsepkov** [atsepkov/RapydScript#45]
Python allows the following:

    a = [None]*10

JS does not, adding it to RS could be useful.

Similarly, in case where the multiplier is a variable, one could let the browser know this ahead of time, to allow its optimization to kick in:

    >>> a = [None]*n

    var a = []; a.length = n;
    for (var _ = 0; _ < a.length; _++) a[_] = None;

**Comment by kovidgoyal** [comment]
Note that in my fork, one can do
``list(n)`` which is equivalent to ``new Array(n)``

Personally, I dont know why one would ever do [None]*n in RS, since presumably the reason to do so in python is to pre-allocate a list -- in RS that is better done with new Array(n).

**Comment by atsepkov** [comment]
Well, it preallocates a list to a certain value. For example, say I want a list of 1000 `1`s: `[1]*1000`. While it has overhead over the case of `new Array(n)`, the user is guaranteed an initial state rather than an array of `undefined`s. And good thing it's not C, where the user would get an array of god-knows-what.

**Comment by kovidgoyal** [comment]
Sure, but IMO the better way for that is to use
x = [None for i in range(n)]
or
x = list(None for i in range(n))
or
x = list(repeat(None, n)) (this of course require someone to write an itertools module for RS, but that is pretty easy to do. 

And if you are worried about performance, this kind of expression can be detected and optimised by the compiler, just as it currently optimises for i in rage9n): loops.

**Comment by kovidgoyal** [comment]
Oh and just to be clear, my objection to this proposal is that this kind of ad hoc syntax addition leads to lots of inconsistency -- and that is something I dislike in programming languages. For instance, if this were to be implemented

```py
a = [None] * 2
b = [None]
c = b * 2
a != c
```

**Comment by atsepkov** [comment]
Agreed, once again bitten by JavaScript's operator limitations. My original idea was to limit this syntax to [...]*n, similar to another inconsistency I already allow:

    a[-1] # compiles to a[a.length-1] as a convenience feature
    b = -1
    a[b] # meaningless/undefined

**Comment by kovidgoyal** [comment]
Yeah, JS sucks :)
I think we should limit this kind of inconsistency to cases where no good alternative exists. In this case, using comprehensions is a good alternative.

**Comment by atsepkov** [comment]
Taking Kovid's advice on this.
