### ISSUE TITLE
...Tried to email you, but received a failed message

### ISSUE THREAD

**Issue by MatthewVita** [atsepkov/RapydScript#52]
...so here's a copy/paste of it

Alexander,

I can't tell you how happy I was when I wrote up:

```python
class Foo:
  def __init__(self):
    console.log("foo")

  def bar(self):
    console.log("baz")

f = Foo()
f.bar()
```

...and saw it perfectly working with RapydScript (Node and in browser). Thank you for your hard work on this tool... Python is my favorite language, but when writing JS, CoffeeScript is way too weird for me and writing in JS (even with ES6) is still a pretty bad experience.

3 quick questions for you:

0) Have you considered renaming the project to something a bit more marketable? Something like "PythonScript" or "PythonJS" kind of like what Golang is doing with its https://github.com/gopherjs/gopherjs ?

1) (This is just me being lazy and asking before I've tried it) but have you successfully hooked up RapydScript with something like Jasmine successfully?

2) Transpilers can be slow, of course. From the demos I'm compiled with RapydScript, it seems pretty fast. Have you seen it working at a good performance with larger codebases? Like 10K+ LoC of RapydScript?

Thanks!

Matthew Vita
www.matthewvita.com

**Comment by MatthewVita** [comment]
...btw this was the err from the email I tried from your website:

```
Delivery to the following recipient failed permanently:

     support@pyjeon.com

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain pyjeon.com by aspmx.l.google.com. [2607:f8b0:4001:c1a::1a].
```

**Comment by atsepkov** [comment]
Hey Matthew, glad you like the compiler. You can use our mailing list to communicate: https://groups.google.com/forum/#!forum/rapydscript and I'll check that my email is updated in the source code.

As for your questions:
0) I actually kept Python out of the name for that exact reason, I don't want people claiming that deviations from Python are a bug, the idea of the language is to create a pleasant and Pythonic experience in JS world and code that compiles to clean JS, not to reproduce Python exactly regardless of overhead. There is also another project called PythonJS (more recently renamed to Rusthon), with very similar goal to mine, I've been talking to its maintainer and we've both been trying to decide which direction to take the projects in (better JS integration/patterns vs better Py integration/patterns). In fact, the Rusthon maintainer just added RapydScript to a supported frontend, which means that via Rusthon project you'll soon be able to compile RS to CoffeeScript, lua, and C++/C as well.

1) I haven't had the need for Jasmine, but I can guarantee with 100% certainty that you can use RS with Jasmine with no extra wrappers/code. This has been the case with all other libraries/frameworks when this question has been asked in the past (AngularJS, jQuery, D3, Mapbox, etc.). The only exceptions you'll see are projects that want to take control and generate JavaScript for you.

2) Yes, grafpad (my original project) is roughly 20k lines of code, even RapydScript compiler itself is 20k lines of code or so, and compiles itself in milliseconds (try ./build after downloading the project). You won't need to worry about compilation speed unless you're doing something wrong in your project.

3) good job starting your counter at 0 :)

**Comment by MatthewVita** [comment]
Thanks for the thoughtful and detailed responses.

I look forward to using RS!
