### ISSUE TITLE
running rapydscript with no options or input hangs

### ISSUE THREAD

**Issue by hartsantler** [atsepkov/RapydScript#57]
when simply running:
```bash
rapydscript
```
the program blocks and prints nothing.  just nitpicking, but it would be nice if running `rapydscript` without options was the same as running `rapydscript --help` or printed a message like: "no input files given"

**Comment by kovidgoyal** [comment]
FYI, this is fixed in my fork. Running rapydscript with no arguments now starts a REPL.

**Comment by atsepkov** [comment]
Fixed a while ago (also starts REPL after integrating Kovid's updates in), forgot to close this.
