### ISSUE TITLE
Pythonic Import, javascript crush 

### ISSUE THREAD

**Issue by nesforge** [atsepkov/RapydScript#61]
Hi Guys,
Thanks for your big efforts to make our life easier and full of magic.

I tried using pythonic import (-n). It works great, but it generates wrong javascript variable name (with dots).

Input:
```python
import views.index.main
```

Output:
```javascript
var views.index.main = (function(){ 
// views_index_main would be valid
})()
```
I know this maybe a known issue, but anyway I felt responsible to let you know.

Have fun!

**Comment by nesforge** [comment]
As I use python to build the frontend I heal that by following:
```python
  import re
  app = open('./server/static/app.js').read() #open original
  
  lst = re.findall(r"var\s+(.*)=",app); #find all js vars
  for key in lst:
      app = app.replace(key, key.replace('.',"_")) #replace all dots with underscore
    
  fixed = open('./server/static/app.js', 'w') #rewrite original
  fixed.write(app)
  fixed.close()
```

And then in the main.pyj : 
```python
  import dir.module.main
  module = dir_module_main
```
It would be easier if the 'as' keyword worked in that case:
```python
  import dir.module.main as module
```

Thanks.

**Comment by kovidgoyal** [comment]
FYI, this is fixed in my fork, see discussion in https://github.com/atsepkov/RapydScript/issues/61

**Comment by kovidgoyal** [comment]
Sorry make that #66

**Comment by nesforge** [comment]
Hi Kovid,
Thank you.
Unfortunately, I don't have much time to study all points in the discussion (66). I hope you guys are going to find a perfect solution.
Then I played with RS + Marionette and it looked highly maintainable. I think in that case python-like modules the last thing before happiness.

**Comment by atsepkov** [comment]
This now works correctly with the new import system. We're even testing for this in `test/imports.pyj` now, see the part about `import_two.sub.sub_var`.
