### ISSUE TITLE
Add some way to detect incomplete input

### ISSUE THREAD

**Issue by kovidgoyal** [atsepkov/RapydScript#64]
I have implement a REPL for RapydScript. The tricky part is determining whether to evaluate the current buffer or start a new line when pressing Enter. 

It would be nice if the RapydScript compiler had some API for determining incomplete input. Currently I use the following heuristic:
Input is incomplete if any of the following conditions are met:

1. Line ends with : or \
2. The error returned by the compiler is for the current line and contains any of the strings: 
  * Unexpected token: eof
  * Unterminated regular expression

This covers most of my use cases, but it would be nice to have a more robust REPL.

**Comment by atsepkov** [comment]
There is no perfect cookie-cutter solution for this. As far as the first bullet, I can name at least a few other situations that signify incomplete input: line ends with a comma, we're currently inside a string (unescaped and unterminated `"""` or `'''` occurs somewhere earlier). I think most of these will trigger unexpected eof error, as you mention, however.

However, if you look at a few other REPL implementations - Python's in particular (bpython, etc.), they don't evaluate the input until the block is finished (rather than trying predict the end of statement). Finishing of the block is signified by 2 consecutive return presses by the user. For a single statement, they evaluate it right away, in which case I think the rules you mention should be good enough.

As far as RS itself, since I based the engine on UglifyJS, I identify end of statement as a position that satisfies `can_insert_semicolon()` call (maybe I should rename it to something like `is_terminated_statement()` instead).

**Comment by kovidgoyal** [comment]
The problem is not so much continuing a block, but identifying when to start a block. i.e. when pressing Enter on the first line should evaluate input or go to next line. As far as block continuation goes, I just keep a block going until the user enters a whitespace only line. 

Thanks, for th tip about can_insert_semicolon, I missed that :)

FYI, the current REPL code is here: https://github.com/kovidgoyal/calibre/blob/master/src/calibre/utils/rapydscript.py#L175 (I still have to add Tab completion, but that should be relatively straightforward)

It's in python (based on an embedded javascript engine for python) so it is not suitable for direct inclusion in your project, but it can probably be ported to RapydScript running on node fairly easily, it's only a couple of hundred lines of code.

Incidentally, since I imagine that the primary users of RapydScript are python developers who need to develop for the browser, would you be willing to consider depending on python + dukpy instead of node for the runtime? I already have rapydscript working in such a context, (as I needed to embed it in a larger python application), so I can easily implement it. 

I have worked on dukpy enough to get it to the point of running the RS compiler. see https://github.com/kovidgoyal/dukpy

**Comment by atsepkov** [comment]
Correct, the primary users would be Python users, but I really don't like the idea of multi-language dependencies, it complicates installation process (even with automated install, something is more likely to go wrong), decreases portability, increases the number of moving parts (making it more likely that something will break when you update libraries), and creates extra overhead. Basically, it increases barrier for entry. My main motivation for picking node was to allow for a self-hosting compiler, this serves 2 advantages:
1. If you're writing code that compiles to JavaScript, your test environment probably already runs JavaScript
2. We eat our own dog food

**Comment by kovidgoyal** [comment]
It's cool, it was only a suggestion. Personally, I find the barrier to entry of installing node higher than installing a python package :) 

The basic REPL is working (apart from TAB completion). Unfortunately, you will need to wait for the next release of calibre to try it out. When that release is done, you can just

```
calibre-debug -c "from calibre.utils.rapydscript import entry; entry()" -- --show-js
```

to run the REPL. 

Currently I am working on the import system, when that is done, I will look into adding TAB completion.

Here is a screenshot:

![repl](https://cloud.githubusercontent.com/assets/1308621/8298145/6f87d01a-1982-11e5-8811-756d831e47ae.png)

**Comment by kovidgoyal** [comment]
I ported the code to javascript, the REPL is now in my fork, you can try it out. I still have to implement a few more things -- recognition for classes defined earlier in the session. Tests for the REPL and completion. But the basic thing is very useable as long as you remember to use new and prototype where needed.

**Comment by kovidgoyal** [comment]
Oh and all the work I have done is now all mixed together in the master branch, which is ~50 commits ahead of your master.

**Comment by kovidgoyal** [comment]
FYI, I just added TAB completion to the REPL, enjoy!
