### ISSUE TITLE
_$rapyd$_Iterable(iterable) does not allow iteration over  an HTMLCollection

### ISSUE THREAD

**Issue by jpcharlesworth** [atsepkov/RapydScript#77]
This problem is related to #70 but qualifies as a separate issue because it applies in single-frame context. In code that interacts with the DOM, one may frequently wish to iterate over these objects but they are only array-like and do not inherit from Array.

The fix is, of course, to add a check on iterable instance of HTMLCollection, returning iterable if true.

**Comment by atsepkov** [comment]
Could you give a couple specific examples where the issue is occurring? That way it will be easier for me to hunt it down and add unit tests.

**Comment by hartsantler** [comment]
i think `document.getElementsByTagName` returns an HTMLCollection.

**Comment by jpcharlesworth** [comment]
The specific case that caused me to post the issue was iterating over the options of a select object. The options are in an HTMLOptionsCollection which is a class derived from HTMLCollection. I think Form elements are in an HTMLCollection and also the rows of a table and cells of a table row.

Because HTMLCollection has a length property, one can always iterate over it by using a range, but unless you need the index for another purpose, using code like
    for item in collection:
        do something
seems more natural.

With reference to hartsantler's suggestion, I think document.getElementsByTagname and the other similar document methods return ordinary javascript arrays.

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/rapydscript-ng/commit/8b654016c90f941c5efc8fc467b2f9566204f7a5

https://github.com/kovidgoyal/rapydscript-ng/commit/d8a32fbcb6a2e3af153c3db85d5c0e43c373d9b2

**Comment by atsepkov** [comment]
Used a different approach here, mainly to account for other iterable types without the additional complexity of parsing object name from `toString()` call. In the future, the plan is to replace it with arr[Symbol.iterable] instead. However, the iterable protocol is part of ES6, and as such dangerous to rely on as the main solution yet.
