### ISSUE TITLE
`rebind_all` dosen't work well

### ISSUE THREAD

**Issue by adousen** [atsepkov/RapydScript#78]
```
class Boy:
    def __init__(self, name):
        self.name = name
        rebind_all(self)

    def greet(self):
        print('My name is' + self.name)

tod = Boy('Tod')
tod.greet()                 # Hello, my name is Tod
getattr(tod, 'greet')()     # Hello, my name is Tod
```

The  example above, copyed from READ.md `Method Binding`, cannot work well.

```
error：Cannot read property 'name' of undefined
```

The compiled js code:

```
    function _$rapyd$_rebindAll(thisArg, rebind) {
        if (typeof rebind === "undefined") {
            rebind = true;
        }
        for (var p in thisArg) {
            if (thisArg[p] && thisArg[p].orig) {
                if (rebind) {
                    thisArg[p] = _$rapyd$_bind(thisArg[p], thisArg);
                } else {
                    thisArg[p] = thisArg[p].orig;
                }
            }
        }
    }
```

I found there is no `_$rapyd$_bind` function definition in this scope, and thisArg[p].orig is undefined.

**Comment by atsepkov** [comment]
I'll take a look, looks like bind is erroneously not getitng triggered

**Comment by atsepkov** [comment]
This is technically fixed by c4104d0b95c2ee095ff2b3ea0f67ec1181d5a0bd but as a side-effect of another bug I introduced (baselib methods that call other methods now auto-trigger an import of the original method, even if the method that caused the trigger is never called in the code).

**Comment by valq7711** [comment]
You have to install somehow from github until @atsepkov  updates npm

**Comment by dewball345** [comment]
ok, wait, so are you saying that you fixed the rebind_all method after I messaged that it didn't work, or are you saying that he already fixed it before I asked?

**Comment by dewball345** [comment]
ok, installed from git and all works well
