### ISSUE TITLE
apply() is not a constructor

### ISSUE THREAD

**Issue by coryell** [atsepkov/RapydScript#79]
I am trying to instantiate an object by unpacking a list its constructor, as in `TestClass(*args)`.

However, this results in an error: "Uncaught TypeError: function apply() { [native code] } is not a constructor".

The following code demonstrates the problem:

    def test_function(*args):
        print(*args)

    class TestClass:
        def __init__(self, *args):
            print(*args)

    args = [1, 2]
    test_function(args) # prints "[1, 2]"
    test_function(*args) # prints "1, 2"
    TestClass(args) # prints "[1, 2]"
    TestClass(*args) # raises "TypeError: function apply() { [native code] } is not a constructor"

The last part of this gets compiled to

    args = [ 1, 2 ];
    test_function(args);
    test_function.apply(this, args);
    new TestClass(args);
    new TestClass.apply(this, args);

The problem seems to be the combination of the `new` keyword with `Constructor.apply()`.

**Comment by kovidgoyal** [comment]
@atsepkov This is fixed in my fork, it should be relatively simple to port the code
https://github.com/kovidgoyal/rapydscript-ng/commit/4383d5ba5ec44ced87b6acbcb510faad35db0ab7

**Comment by atsepkov** [comment]
Closed with c4104d0b95c2ee095ff2b3ea0f67ec1181d5a0bd, after reverting to original args/kwargs system and addressing special cases properly, issue went away.
