### ISSUE TITLE
multi-line regex syntax

### ISSUE THREAD

**Issue by atsepkov** [atsepkov/RapydScript#83]
I'd really like to add something along the lines of verbose/multiline regex to RapydScript. Something like this, which CoffeeScript already supports:

    emailPattern = /// ^ #begin of line
       ([\w.-]+)         #one or more letters, numbers, _ . or -
       @                 #followed by an @ sign
       ([\w.-]+)         #then one or more letters, numbers, _ . or -
       \.                #followed by a period
       ([a-zA-Z.]{2,6})  #followed by 2 to 6 letters or periods
       $ ///i            #end of line and ignore case

**Comment by kovidgoyal** [comment]
This is already implemented in my fork. IIRC I implemented it both with the above syntax and using python's verbose mode in the stdlib re module.

**Comment by atsepkov** [comment]
Thanks, I'll take a look!

**Comment by atsepkov** [comment]
Implemented this back in the fall of last year, forgot to close the issue.
