### ISSUE TITLE
multi-line list : peculiar syntax error

### ISSUE THREAD

**Issue by JohnDenker** [atsepkov/RapydScript#85]
#### Context, Example
```
foo = [1,
        2,
        3]

print(foo)
```

#### Expected and Desired Behavior
This works just fine in standard python:
```
[1, 2, 3]
```

#### Observed Behavior
```
Unexpected token num «3», expected punc «,»
```

#### Workarounds

* Putting the entire RHS within parentheses makes it compile OK
* Putting line-continuation marks "\" on the RHS makes it compile OK

**Comment by kovidgoyal** [comment]
@atsepkov This is fixed in my fork, although I have no actual memory of fixing it :)
So I cannot point you to a particular commit, sorry.

**Comment by atsepkov** [comment]
Looks like it's fixed in my branch too now, similarly I have no idea when or how.
