### ISSUE TITLE
So , no release yet? 

### ISSUE THREAD

**Issue by v3ss0n** [atsepkov/RapydScript#87]
Waiting for a release  tag.

**Comment by atsepkov** [comment]
hmm, I never thought about using tags. I guess I'll create one once I'm done merging bug fixes.

**Comment by v3ss0n** [comment]
Having a release  , a regular one will boost RapydScript popularity.

**Comment by atsepkov** [comment]
I use version bumps in package.json to signify a "release", and publish them to npm. If you want something akin to a release use `npm install rapydscript`.

**Comment by FeralBytes** [comment]
Should this be closed now?

**Comment by FeralBytes** [comment]
@v3ss0n Thanks.
