### ISSUE TITLE
All of the examples from http://salvatore.diodev.fr are down.

### ISSUE THREAD

**Issue by v3ss0n** [atsepkov/RapydScript#88]
everything from http://salvatore.diodev.fr is down.
http://salvatore.diodev.fr/RapydScript - nginx 502-bad gateway.

**Comment by atsepkov** [comment]
Yep, Salvatore has sent me an email earlier saying that his server went down (he's another RapydScript user who has taken it upon himself to build an examples website). He has a backup at http://salvatore.pythonanywhere.com/RapydScript, use that for now and if his main server continues to stay down, I will change to link to point to this mirror.

**Comment by artyprog** [comment]
Hy Alex,
From now on, the examples will be hosted on http://salvatore.pythonanywhere.com/RapydScript
Although I manage to restart my own server, it's no as reliable as it should be.
Regards

**Comment by atsepkov** [comment]
Thanks, will update the README. By the way, I got another surprise for the
community I'm planning to implement this Friday/Saturday, stay tuned. I
think the community will enjoy it.

**Comment by v3ss0n** [comment]
hey , host them on Openshift? It is free and very reliable.

**Comment by artyprog** [comment]
I like suprises :-)
Thank you Alex

2015-09-15 17:29 GMT+02:00 Alexander Tsepkov <notifications@github.com>:

**Comment by artyprog** [comment]
@v3ss0n 
That you for your suggestion but pythonanywhere si very Nice and profès signal too

**Comment by atsepkov** [comment]
Btw, I can vouch for openshift as well, I use it to host rapydscript.com. I'll change the URL to pythonanywhere in the README.

**Comment by atsepkov** [comment]
Fixed, examples now link to pythonanywhere.
