### ISSUE TITLE
class declaration with no base-class args

### ISSUE THREAD

**Issue by JohnDenker** [atsepkov/RapydScript#96]
#### Context
```
class trivial():                # note the ()
  def __init__(self):
    0000
```

#### Desired and Expected Behavior (regular python)
This is accepted by python2.7, python3.4, ipython2.7, and ipython3.  So far so good.

#### Observed Behavior (RS)
```

ERROR: Unexpected token: punc «)» [/home/jsd/physics/python-class.py:3,14]

/usrsrc/RapydScript/lib/parse.js:145
    throw new JS_Parse_Error(message, line, col, pos, is_eof);
          ^
Error
    at new JS_Parse_Error (/usrsrc/RapydScript/lib/parse.js:132:18)
    at js_error (/usrsrc/RapydScript/lib/parse.js:145:11)
    at croak (/usrsrc/RapydScript/lib/parse.js:753:145)
    at token_error (/usrsrc/RapydScript/lib/parse.js:758:9)
    at unexpected (/usrsrc/RapydScript/lib/parse.js:764:9)
    at expr_atom (/usrsrc/RapydScript/lib/parse.js:1879:13)
    at /usrsrc/RapydScript/lib/parse.js:1428:25
    at class_ (/usrsrc/RapydScript/lib/parse.js:1434:15)
    at /usrsrc/RapydScript/lib/parse.js:1051:24
    at /usrsrc/RapydScript/lib/parse.js:795:20
```

#### Workaround
Leave off the ()

**Comment by kovidgoyal** [comment]
Wow, you *really* like the superfluous parentheses :)

https://github.com/kovidgoyal/rapydscript-ng/commit/5ba1124c0c9c763a72b7ddf147e2dde5b79090a7

**Comment by atsepkov** [comment]
Btw @kovidgoyal feel free to do pull requests so you get credit for these fixes in the main fork, it's only when pull request breaks backwards compatibility or contains 1-month worth of changes that I'm hesitant about merging it.

**Comment by kovidgoyal** [comment]
The codebases have diverged too much to make pull requests practical at this point. I'd essentially have to do the fix twice, once to my codebase and once to yours, so while credit would be nice, it is too much work. I'm just happy to have the fixes make it back to the main branch, no matter the byline :)

**Comment by JohnDenker** [comment]
Since you ask:  Here's where I'm coming from on this (and on a host of other issues):

I don't like superfluous parentheses any more than you do.  What I like is ***productivity***.  As a corollary, I like ***portability***.  That is, I like being able to cut-and-paste code that other folks have written.  I don't want to optimize it, I don't want to analyze it, I don't want to rewrite it, I don't want to wonder whether it will compile, and I super-especially don't want to wonder whether it will run correctly.

This is why I report compatibility issues, even there is an obvious workaround ... and double-especially when there isn't.

**Comment by kovidgoyal** [comment]
I totally agree with you on compatibility. Which is why I fixed the issue, I was just trying for a little humour :)

**Comment by hartsantler** [comment]
@JohnDenker  " I don't want to optimize it, I don't want to analyze it, I don't want to rewrite it..."
clam the fuck down.

**Comment by atsepkov** [comment]
This works for 80% of the code, but not for all Python code. While I too like ability to copy-paste code without thinking about it, thinking that your Python code will just run in RapydScript without any massaging on your end is dangerous. I'm not saying omissions like these are "features" of the language but if you don't bother to do any gut-checks on what you're porting, sooner or later you'll be bitten by it.

Nothing scares me more than a developer who thinks his work is done because "compile" button doesn't return any errors.
