### ISSUE TITLE
Type Annotations

### ISSUE THREAD

**Issue by atsepkov** [atsepkov/RapydScript#97]
Already mentioned this idea on the mailing list a few months ago, but wanted to document it in a task too so I have something concrete. Python 3 adds type annotations. There are a few libraries that extend that logic into static typing (which is actually the best use of type annotations I see anyway). There are also a few languages that have used similar syntax to actually enforce static typing (TypeScript, Swift). Adding optional static typing to RapydScript may allow for better compile-time safety and perhaps even optimizations in the future. For example:

    def test(a: Number, b: Number, c: String) -> String:
        return a + b + c

The above function now has enough information to throw a compile-time error, since `c` can't be added to either `a` or `b` without typecasting first. Using the above approach we also have enough information to allow per-function operator overloading without using special syntax:

    def matrixMath(a: Matrix, b: Matrix) -> Matrix:
        return a * b

The compiler now has enough information to know that the intent here is to use overloaded version of multiplication since `Matrix` is a class (which was defined earlier).

As for conventions, I prefer JavaScript type names because they're more consistent that Python. Whereas Python uses lowercase for most internal classes but suggests upper-camel-case for your own, JavaScript uses upper-camel-case for both, making it easy for the user to tell that the item is a class:

    Number:  assume float
    Boolean: boolean
    Integer:   assume integer (custom type)
    String:     string
    Date:       date
    RegExp:  regular expression
    [Number]: array of numbers
    [Object]:   array of objects (object is a vague definition for any subtype item)
    [[Number]]: matrix-like structure
    {String: Number}: hash with keys being strings and values being numbers

Similar to Swift, `Object` would identify `AnyObject`. I haven't yet considered if it makes sense to have the concept of `AnyType` (any primitive) and `AnyObject` (any non-primitive) item yet.

When type annotations are used in a given scope, the compiler can also start enforcing that type of locals not change after definition:

    def test(a: Number) -> Number:
        b = 5        # ok
        b += 1       # ok
        if True: b = 'something else'  # compile error, assignment of string to number-type
        return b + a

**Comment by kovidgoyal** [comment]
IMO

1) One of the goals of RapydScript is to be an environment that is comfortable for python programmers. Using JS type names over python type names is in conflict with that goal, for a very minor gain

2) Changing operator behavior based on type annotations is a bad idea. It can lead to all sorts of inconsistencies. 

  a) container membership tests like index(), find() and has() will then behave differently from looping over the container and testing for equality (depending on the annotations). 

  b) Copy pasting a block of code into a different function could potentially alter its behavior

**Comment by atsepkov** [comment]
1. It's difficult to come up with a good solution here. I wouldn't call convention consistency a very minor gain, to me personally that gain is pretty important. We have deviated from Python in the past in cases where its consistency didn't make sense (i.e. lambda function). Moreover, if you want to create a new object of that type in RS, the best way to do it is by calling the JavaScript constructor. `String` makes sense to me because `String(thing)` creates a string object from thing, `str()` works too but is a wrapper around `JSON.stringify`. Since there are relatively few keywords allowed for type annotation anyway, I don't see a problem with allowing Pythonic aliases too (str, int, float, dict, list). Let me know what you think of this compromise.

2. Perhaps, but wouldn't these only affect non-primitive types rather than primitive ones? Types for which the primitive operators already perform non-sensical operations ([1,2] + [3,4]).
    1. I'm not following, could you give an example? I also don't intend the overloading to leak into functions called within the statically-typed function, if that's what you mean here.
    2. This is already the case with the `strict` directive. A developer who copy-pastes code without proof-reading it is not doing his job. We're already expected to update the variable names after copy-pasting, how is this different? Moreover, the idea is to only apply overloading to non-primitive types and I don't see where combining non-primitive types using primitive operators of original code would have produced the intended result (`[1,2] + [3] = '1,23'`, `{} + {'a':'b'} = '[object Object][object Object]'`, `{} + [] = 0`, `[] + {} = '[object Object]'`, `[1] - 2 = -1`, `[1,2] - 2 = NaN`, is any of those desirable?).

**Comment by kovidgoyal** [comment]
1. I am fine with allowing both forms of the type name.

2. 
a) Here is contrived example
```py
def f(list:list-of-MyClass, q:MyClass):
   for i in list:
      if q == i:
          return True
   return False

def f2(list:list-of-MyClass, q:MyClass):
     return list.index(q) != -1

f1(a, b) != f2(a, b)
```

b. There is no strict directive in RS. One of the selling points of RS is that it is supposed to make programming easier by imposing some consistency on the insanity that is JS. Consider this example:

```py

def f(a:MyClass, b:MyClass):
   .... lots of code
   ... somewhere in the middle of all that: a + b
   ...

```
Now copy paste that code to another function without annotations and you will get an incorrect result. It's all very well to say that it is upto the developer to do his job right, but it is also up to us to not introduce features into the language that make it particularly easy to screw up for the unwary developer.

**Comment by atsepkov** [comment]
a. If list uses native `indexOf` operation, sure. But doesn't this problem already exist in current compiler too? If I use deep-equality instead of `q == i` won't I run into the same issue? If user does `from future import equality` as suggested in another thread, won't same issue still arise?

b. I was talking about strict directive of JS, which makes JS logic behave differently in a given scope (although admittedly JS isn't the best example of how to do things right, in this case I like how they implemented it in terms of scoping). Also, the example you gave doesn't disprove the point I made earlier, sure there is `a + b` in the middle, but the only thing that would have produced in old code is `"[object Object][object Object]"` string. My question remains, do you think that's what the developer intended in original code? I can't think of any use case (although I'm sure there is some obscure one) where native JavaScript behavior for class-like objects produces the intended result. They all suffer from the same flaw in that they stringify the data and run the operation on the string.

**Comment by kovidgoyal** [comment]
a. No it does not exist in the current compiler. The fact that it would start existing is the major reason why I have not implemented ```from future import equality```, as I mentioned in that thread. Certainly if you use deep equality you will run into this issue, but then you are already aware of the issue otherwise you would not be using deep equality in the first place. The problem is that having index() and loop with == do different things is highly counter-intuitive.

b. No, in the original function, as per your proposal, the + operator would be overloaded because of the type annotations and therefore do the right thing, namely ```a.__iadd__(b)``` but when the code is copy-pasted to another function without annotations, it would result in ```a.toString() + b.toString()```.

**Comment by hartsantler** [comment]
i recommend using that type names i use in rusthon where possible, they are all lower case:
* string
* int, int32, i32
* float, f32
* float64, f64, double
* short, int16, i16

https://github.com/rusthon/Rusthon/wiki/JavaScript-Static-Types

https://github.com/rusthon/Rusthon/blob/master/regtests/lang/typedarrays.py
