### ISSUE TITLE
lambda expressions not working

### ISSUE THREAD

**Issue by JohnDenker** [atsepkov/RapydScript#99]
#### Context
```
print(map((lambda x: [x, x**2]), range(5)))
```
#### Expected and Desired Behavior (regular python)
```
[[0, 0], [1, 1], [2, 4], [3, 9], [4, 16]]
```
#### Observed Behavior (RS)
```
ERROR: Unexpected token name «x», expected punc «)» [/home/jsd/physics/python-lambda.py:2,18]

/usrsrc/RapydScript/lib/parse.js:145
    throw new JS_Parse_Error(message, line, col, pos, is_eof);
```
#### Non-workaround
Generator expressions don't seem to be working either; see item #100 
#### Workaround
Define a named function.

**Comment by kovidgoyal** [comment]
as is noted in the readme, this is by design. You need to use def() for anonymous functions
